import { useEffect, useState } from "react";
import { BarChart3, CalendarCheck2, CalendarClock, ChartNoAxesColumnIncreasing, ClipboardCheck, Stethoscope, TrendingUp, UserRoundCheck, Users } from "lucide-react";
import { useParams } from "react-router-dom";
import { apiRequest } from "@/api/client";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { useAuth } from "@/context/auth-context";
import { useRealtimeRevision } from "@/realtime/useRealtimeRevision";

const statDefinitions = [
  { key: "scheduled", label: "Scheduled today", icon: CalendarClock, tone: "bg-blue-50 text-blue-700" },
  { key: "checkedIn", label: "Checked in", icon: CalendarCheck2, tone: "bg-teal-50 text-teal-700" },
  { key: "completed", label: "Completed today", icon: ClipboardCheck, tone: "bg-emerald-50 text-emerald-700" },
];
const statusData = (values) => [
  { key: "scheduled", label: "Scheduled", value: values.scheduled, color: "bg-blue-500", text: "text-blue-700" },
  { key: "checkedIn", label: "Checked in", value: values.checkedIn, color: "bg-teal-600", text: "text-teal-700" },
  { key: "completed", label: "Completed", value: values.completed, color: "bg-emerald-500", text: "text-emerald-700" },
];
const shortDate = (value) => new Intl.DateTimeFormat("en", { month: "short", day: "numeric", timeZone: "UTC" }).format(new Date(`${value}T00:00:00Z`));

function AppointmentStatusChart({ values }) {
  const data = statusData(values); const max = Math.max(...data.map((item) => item.value), 1); const total = data.reduce((sum, item) => sum + item.value, 0);
  return <Card className="bg-white shadow-none"><CardHeader><div className="flex items-start gap-3"><div className="grid size-10 place-items-center rounded-md bg-blue-50 text-blue-700"><BarChart3 className="size-5" /></div><div><CardTitle className="text-lg">Appointments by status</CardTitle><CardDescription className="mt-1">Current workload distribution for this branch.</CardDescription></div></div></CardHeader><CardContent><div className="flex h-52 items-end justify-around gap-5 border-b border-slate-200 px-3 pt-6">{data.map((item) => <div key={item.key} className="flex h-full flex-1 flex-col items-center justify-end"><span className={`mb-2 text-xl font-semibold ${item.text}`}>{item.value}</span><div className={`w-full max-w-20 rounded-t-md ${item.color} transition-all`} style={{ height: `${Math.max((item.value / max) * 135, item.value ? 12 : 3)}px`, opacity: item.value ? 1 : 0.2 }} /></div>)}</div><div className="mt-3 grid grid-cols-3 gap-2 text-center">{data.map((item) => <div key={item.key}><span className={`mx-auto mb-1 block size-2 rounded-full ${item.color}`} /><p className="text-xs text-muted-foreground">{item.label}</p></div>)}</div><p className="mt-4 border-t pt-3 text-xs text-muted-foreground"><span className="font-semibold text-slate-900">{total}</span> appointments recorded in this location</p></CardContent></Card>;
}

function AppointmentTrendChart({ data }) {
  const max = Math.max(...data.map((item) => item.count), 1);
  return <Card className="bg-white shadow-none"><CardHeader><div className="flex items-start gap-3"><div className="grid size-10 place-items-center rounded-md bg-teal-50 text-teal-700"><TrendingUp className="size-5" /></div><div><CardTitle className="text-lg">Appointments over time</CardTitle><CardDescription className="mt-1">Daily appointment volume over the last 7 days.</CardDescription></div></div></CardHeader><CardContent><div className="relative flex h-52 items-end gap-2 border-b border-l border-slate-200 px-2 pt-6 sm:gap-3">{data.map((item) => <div key={item.date} className="group flex h-full min-w-0 flex-1 flex-col items-center justify-end"><span className="mb-1 text-xs font-semibold text-teal-800">{item.count}</span><div className="w-full max-w-10 rounded-t bg-teal-600 transition hover:bg-teal-700" style={{ height: `${Math.max((item.count / max) * 135, item.count ? 10 : 2)}px`, opacity: item.count ? 1 : 0.18 }} /></div>)}</div><div className="mt-2 flex gap-2 pl-2 sm:gap-3">{data.map((item) => <p key={item.date} className="min-w-0 flex-1 text-center text-[10px] text-muted-foreground sm:text-xs">{shortDate(item.date)}</p>)}</div></CardContent></Card>;
}

function DoctorVolumeChart({ doctors }) {
  const max = Math.max(...doctors.map((doctor) => doctor.completedTotal), 1);
  return <Card className="bg-white shadow-none"><CardHeader><div className="flex items-start gap-3"><div className="grid size-10 place-items-center rounded-md bg-violet-50 text-violet-700"><ChartNoAxesColumnIncreasing className="size-5" /></div><div><CardTitle className="text-lg">Patients seen per doctor</CardTitle><CardDescription className="mt-1">Finalized encounters by active doctor in this location.</CardDescription></div></div></CardHeader><CardContent>{doctors.length === 0 ? <p className="rounded-md bg-slate-50 p-8 text-center text-sm text-muted-foreground">No active doctor data to chart.</p> : <div className="space-y-4">{doctors.map((doctor) => <div key={doctor.id} className="grid items-center gap-2 sm:grid-cols-[180px_1fr_44px]"><div className="min-w-0"><p className="truncate text-sm font-medium">{doctor.name}</p><p className="truncate text-xs text-muted-foreground">{doctor.email}</p></div><div className="h-7 overflow-hidden rounded-md bg-slate-100"><div className="flex h-full items-center rounded-md bg-gradient-to-r from-teal-600 to-teal-500 px-2 text-xs font-medium text-white transition-all" style={{ width: `${Math.max((doctor.completedTotal / max) * 100, doctor.completedTotal ? 8 : 0)}%` }}>{doctor.completedTotal > 0 && doctor.completedTotal}</div></div><p className="text-right text-sm font-semibold">{doctor.completedTotal}</p></div>)}</div>}</CardContent></Card>;
}

export function AdminAnalyticsDashboard() {
  const realtimeRevision = useRealtimeRevision(["patient:created", "appointment:created", "appointment:updated", "encounter:finalized", "staff:created"]);
  const { tenantSlug, locationSlug } = useParams(); const { session } = useAuth(); const [analytics, setAnalytics] = useState(null); const [error, setError] = useState("");
  useEffect(() => { let active = true; apiRequest(`/${tenantSlug}/${locationSlug}/analytics`, { headers: { Authorization: `Bearer ${session.accessToken}` } }).then((data) => { if (active) setAnalytics(data); }).catch((requestError) => { if (active) setError(requestError.message); }); return () => { active = false; }; }, [locationSlug, realtimeRevision, session.accessToken, tenantSlug]);
  if (error) return <div className="rounded-md border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>;
  if (!analytics) return <div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[1, 2, 3, 4].map((item) => <div key={item} className="h-36 animate-pulse rounded-lg border bg-white" />)}</div>;
  return <><p className="text-sm font-medium text-teal-700">Location intelligence</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Operational overview</h1><p className="mt-2 text-muted-foreground">Read-only performance, scheduling utilization and clinical activity for this branch.</p>
    <section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card className="bg-white shadow-none"><CardContent className="p-5"><div className="flex items-start justify-between"><div><p className="text-sm font-medium text-muted-foreground">Registered patients</p><p className="mt-3 text-3xl font-semibold">{analytics.patients.total}</p></div><div className="grid size-10 place-items-center rounded-md bg-violet-50 text-violet-700"><Users className="size-5" /></div></div><div className="mt-4 flex items-center gap-2 border-t pt-3 text-xs text-muted-foreground"><UserRoundCheck className="size-4 text-teal-700" /><span className="font-semibold text-slate-900">{analytics.patients.today}</span> registered today</div></CardContent></Card>{statDefinitions.map((stat) => { const Icon = stat.icon; return <Card key={stat.key} className="bg-white shadow-none"><CardContent className="p-5"><div className="flex items-start justify-between"><div><p className="text-sm font-medium text-muted-foreground">{stat.label}</p><p className="mt-3 text-3xl font-semibold">{analytics.appointmentsToday[stat.key]}</p></div><div className={`grid size-10 place-items-center rounded-md ${stat.tone}`}><Icon className="size-5" /></div></div><p className="mt-4 border-t pt-3 text-xs text-muted-foreground">Current branch · today</p></CardContent></Card>; })}</section>
    <section className="mt-6 grid gap-6 xl:grid-cols-2"><AppointmentStatusChart values={analytics.appointmentsByStatus} /><AppointmentTrendChart data={analytics.appointmentsLast7Days} /></section>
    <div className="mt-6"><DoctorVolumeChart doctors={analytics.doctors} /></div>
    <Card className="mt-6 bg-white shadow-none"><CardHeader><div className="flex items-start gap-3"><div className="grid size-10 place-items-center rounded-md bg-teal-50 text-teal-700"><Stethoscope className="size-5" /></div><div><CardTitle className="text-lg">Doctor activity</CardTitle><CardDescription className="mt-1">Completed patient visits backed by finalized encounters.</CardDescription></div></div></CardHeader><CardContent className="p-0">{analytics.doctors.length === 0 ? <div className="px-6 py-12 text-center"><p className="font-medium">No active doctors</p></div> : <Table><TableHeader><TableRow><TableHead>Doctor</TableHead><TableHead>Completed today</TableHead><TableHead>Completed total</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{analytics.doctors.map((doctor) => <TableRow key={doctor.id}><TableCell><p className="font-medium">{doctor.name}</p><p className="text-xs text-muted-foreground">{doctor.email}</p></TableCell><TableCell className="font-semibold">{doctor.completedToday}</TableCell><TableCell className="font-semibold">{doctor.completedTotal}</TableCell><TableCell><Badge variant="verified">Active</Badge></TableCell></TableRow>)}</TableBody></Table>}</CardContent></Card>
  </>;
}
