import { useState } from "react";
import { Bot, Check, RotateCcw, Sparkles, Trash2 } from "lucide-react";
import { apiRequest } from "@/api/client";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";

const stamp = (value) => new Intl.DateTimeFormat("en-PK", { dateStyle: "medium", timeStyle: "short", hour12: true }).format(new Date(value));
export function AiSummaryPanel({ root, headers, encounter, notes, onAccepted }) {
  const finalized = encounter.status === "finalized"; const accepted = encounter.aiSummary?.text;
  const [suggestion, setSuggestion] = useState(""); const [generatedAt, setGeneratedAt] = useState(null); const [generating, setGenerating] = useState(false); const [accepting, setAccepting] = useState(false); const [error, setError] = useState("");
  async function generate() { setGenerating(true); setError(""); try { await apiRequest(`${root}/encounters/${encounter._id}`, { method: "PATCH", headers, body: JSON.stringify(notes) }); const data = await apiRequest(`${root}/encounters/${encounter._id}/ai-summary`, { method: "POST", headers }); setSuggestion(data.suggestion.text); setGeneratedAt(data.suggestion.generatedAt); } catch (requestError) { setError(requestError.message); } finally { setGenerating(false); } }
  async function accept() { setAccepting(true); setError(""); try { const data = await apiRequest(`${root}/encounters/${encounter._id}/ai-summary`, { method: "PATCH", headers, body: JSON.stringify({ text: suggestion, generatedAt }) }); onAccepted(data.encounter); setSuggestion(""); setGeneratedAt(null); } catch (requestError) { setError(requestError.message); } finally { setAccepting(false); } }
  if (finalized && !accepted) return null;
  if (accepted && (finalized || !suggestion)) return <Card className="mt-6 border-violet-200 bg-gradient-to-br from-violet-50 to-white shadow-none"><CardHeader><div className="flex items-start justify-between gap-4"><div className="flex gap-3"><div className="grid size-10 place-items-center rounded-md bg-violet-100 text-violet-700"><Bot className="size-5" /></div><div><CardTitle className="text-lg">Clinical Summary (AI-assisted)</CardTitle><CardDescription className="mt-1">Clinician-reviewed and explicitly accepted; original structured notes remain authoritative.</CardDescription></div></div><Badge variant={finalized ? "finalized" : "verified"}>{finalized ? "locked" : "accepted"}</Badge></div></CardHeader><CardContent><p className="whitespace-pre-wrap text-sm leading-6 text-slate-700">{accepted}</p><div className="mt-4 flex flex-wrap gap-2 border-t pt-3 text-xs text-muted-foreground"><span>Provider: Groq</span><span>·</span><span>Model: {encounter.aiSummary.model}</span><span>·</span><span>Accepted: {stamp(encounter.aiSummary.acceptedAt)}</span></div>{!finalized && <Button variant="outline" size="sm" className="mt-4" onClick={generate} disabled={generating}><RotateCcw className="mr-2 size-4" />{generating ? "Generating…" : "Generate a new suggestion"}</Button>}{error && <p className="mt-3 text-sm text-red-700">{error}</p>}</CardContent></Card>;
  return <Card className="mt-6 border-violet-200 bg-gradient-to-br from-violet-50 to-white shadow-none"><CardHeader><div className="flex gap-3"><div className="grid size-10 place-items-center rounded-md bg-violet-100 text-violet-700"><Sparkles className="size-5" /></div><div><CardTitle className="text-lg">AI-assisted clinical summary</CardTitle><CardDescription className="mt-1">Optional recommendation only. Mandatory clinician review applies.</CardDescription></div></div></CardHeader><CardContent>{suggestion ? <div className="space-y-4"><div className="rounded-lg border border-violet-200 bg-white p-4"><div className="mb-2 flex items-center gap-2 text-sm font-semibold text-violet-900"><Bot className="size-4" /> AI Suggested Summary — review before using</div><Textarea className="min-h-36 border-violet-200" value={suggestion} onChange={(event) => setSuggestion(event.target.value)} /></div><div className="flex justify-end gap-2"><Button variant="outline" onClick={() => { setSuggestion(""); setGeneratedAt(null); setError(""); }}><Trash2 className="mr-2 size-4" /> Discard</Button><Button className="bg-violet-700 hover:bg-violet-800" onClick={accept} disabled={accepting || !suggestion.trim()}><Check className="mr-2 size-4" />{accepting ? "Saving…" : "Accept & Save"}</Button></div></div> : <Button className="bg-violet-700 hover:bg-violet-800" onClick={generate} disabled={generating}><Sparkles className="mr-2 size-4" />{generating ? "Generating AI summary…" : "Generate AI Summary"}</Button>}{error && <div className="mt-4 rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}<p className="mt-4 text-xs text-muted-foreground">Generate/discard never changes the original note. AI assistance is always optional and never blocks finalization.</p></CardContent></Card>;
}
