import { Plus, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

const emptyItem = () => ({ medicineName: "", strength: "", frequency: "", duration: "", instructions: "" });

export function PrescriptionPanel({ items = [], onChange, disabled }) {
  const update = (index, key, value) => onChange(items.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value } : item));
  return <Card className="bg-white shadow-none"><CardHeader><div className="flex items-center justify-between gap-3"><div><CardTitle className="text-lg">Prescription</CardTitle><CardDescription>{disabled ? "Issued medicines are locked with the finalized encounter." : "Add medicines only when you want to issue a prescription for this visit."}</CardDescription></div>{!disabled && <Button type="button" variant="outline" size="sm" onClick={() => onChange([...items, emptyItem()])}><Plus className="mr-1 size-4" />Add medicine</Button>}</div></CardHeader><CardContent>{items.length ? <div className="space-y-4">{items.map((item, index) => <div key={item._id || index} className="rounded-xl border bg-slate-50 p-4"><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-sm font-semibold">Medicine name<input disabled={disabled} className="min-h-10 rounded-md border bg-white px-3 font-normal" value={item.medicineName || ""} onChange={(event) => update(index, "medicineName", event.target.value)} /></label><label className="grid gap-1 text-sm font-semibold">Strength<input disabled={disabled} className="min-h-10 rounded-md border bg-white px-3 font-normal" placeholder="e.g. 500 mg" value={item.strength || ""} onChange={(event) => update(index, "strength", event.target.value)} /></label><label className="grid gap-1 text-sm font-semibold">Frequency<input disabled={disabled} className="min-h-10 rounded-md border bg-white px-3 font-normal" placeholder="e.g. Once daily" value={item.frequency || ""} onChange={(event) => update(index, "frequency", event.target.value)} /></label><label className="grid gap-1 text-sm font-semibold">Duration<input disabled={disabled} className="min-h-10 rounded-md border bg-white px-3 font-normal" placeholder="e.g. 7 days" value={item.duration || ""} onChange={(event) => update(index, "duration", event.target.value)} /></label></div><label className="mt-3 grid gap-1 text-sm font-semibold">Instructions (optional)<input disabled={disabled} className="min-h-10 rounded-md border bg-white px-3 font-normal" placeholder="e.g. Take after breakfast" value={item.instructions || ""} onChange={(event) => update(index, "instructions", event.target.value)} /></label>{!disabled && <Button type="button" variant="ghost" size="sm" className="mt-3 text-red-700 hover:text-red-800" onClick={() => onChange(items.filter((_, itemIndex) => itemIndex !== index))}><Trash2 className="mr-1 size-4" />Remove</Button>}</div>)}</div> : <p className="rounded-lg border border-dashed bg-slate-50 p-4 text-sm text-muted-foreground">No prescription will be issued unless you add a medicine.</p>}</CardContent></Card>;
}
