import { CalendarPlus2, PhoneCall, Stethoscope } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

const timeframeLabels = { "1_week": "Within 1 week", "2_weeks": "Within 2 weeks", "1_month": "Within 1 month" };

export function RecallRequestsPanel({ recallRequests, onSchedule }) {
  return <Card className="mt-8 overflow-hidden border-teal-200 bg-white shadow-none"><CardHeader className="border-b bg-gradient-to-r from-teal-50 to-white"><div className="flex items-start gap-3"><span className="grid size-10 place-items-center rounded-lg bg-teal-700 text-white"><PhoneCall className="size-5" /></span><div><CardTitle className="text-lg">Recall requests</CardTitle><CardDescription className="mt-1">Patients who agreed to arrange a follow-up. Front-desk selects the actual appointment slot.</CardDescription></div></div></CardHeader><CardContent className="p-0">{recallRequests.length === 0 ? <div className="px-6 py-9 text-center"><p className="text-sm font-medium">No pending recall requests</p><p className="mt-1 text-xs text-muted-foreground">Coordinator handoffs will appear here after patient agreement.</p></div> : <div className="divide-y">{recallRequests.map((recall) => <article key={recall._id} className="flex flex-col justify-between gap-4 p-5 lg:flex-row lg:items-center"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{recall.patientId?.name}</p><Badge className="border-amber-200 bg-amber-50 text-amber-700">{timeframeLabels[recall.timeframe]}</Badge></div><p className="mt-1 flex items-center gap-1.5 text-xs text-muted-foreground"><Stethoscope className="size-3.5 text-teal-700" />{recall.doctorId?.name} · {recall.carePlanId?.goal}</p><p className="mt-3 max-w-2xl rounded-md bg-slate-50 px-3 py-2 text-sm leading-6 text-slate-600">{recall.note}</p><p className="mt-2 text-xs text-muted-foreground">Requested by {recall.requestedByUserId?.name}</p></div><Button className="shrink-0 bg-teal-700 hover:bg-teal-800" onClick={() => onSchedule(recall)}><CalendarPlus2 className="mr-2 size-4" /> Schedule follow-up</Button></article>)}</div>}</CardContent></Card>;
}
