import { useEffect, useState } from "react";
import { LayoutDashboard, LogOut, UserCircle } from "lucide-react";
import { NavLink, Outlet, useLocation, useNavigate, useParams } from "react-router-dom";
import { MeridianSidebarBrand, SidebarUserCard } from "@/components/MeridianSidebarBrand";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/context/auth-context";
import { cn } from "@/lib/utils";

export function TenantLayout() {
  const { tenantSlug } = useParams(); const navigate = useNavigate(); const route = useLocation();
  const { session, logout } = useAuth(); const [mobileOpen, setMobileOpen] = useState(false);
  useEffect(() => { setMobileOpen(false); }, [route.pathname]);
  useEffect(() => { document.body.style.overflow = mobileOpen ? "hidden" : ""; return () => { document.body.style.overflow = ""; }; }, [mobileOpen]);
  function signOut() { logout(); navigate("/login", { replace: true }); }
  const sidebar = <><MeridianSidebarBrand /><nav className="flex-1 p-3 pt-5"><p className="mb-2 px-3 text-[10px] font-semibold uppercase tracking-[0.16em] text-slate-400">Organization</p><NavLink to={`/${tenantSlug}/overview`} className="flex items-center gap-3 rounded-lg border border-slate-700 bg-slate-800 px-2.5 py-2 text-sm font-medium text-white shadow-[inset_3px_0_0_#2dd4bf]"><span className="grid size-8 place-items-center rounded-md bg-slate-700 text-teal-300"><LayoutDashboard className="size-4" /></span>Overview</NavLink></nav><SidebarUserCard user={session.user} roleLabel="Clinic Admin" /></>;
  return <div className="min-h-screen min-w-0 overflow-x-hidden bg-slate-50 text-slate-950"><aside className="fixed inset-y-0 left-0 z-30 hidden w-64 flex-col border-r border-slate-800 bg-slate-950 text-white md:flex">{sidebar}</aside><button type="button" aria-label="Close navigation" className={cn("fixed inset-0 z-40 bg-slate-950/55 transition-opacity md:hidden", mobileOpen ? "opacity-100" : "pointer-events-none opacity-0")} onClick={() => setMobileOpen(false)} /><aside className={cn("fixed inset-y-0 left-0 z-50 flex w-[min(82vw,18rem)] flex-col bg-slate-950 text-white shadow-2xl transition-transform duration-300 md:hidden", mobileOpen ? "translate-x-0" : "-translate-x-full")}>{sidebar}</aside><div className="min-w-0 md:pl-64"><header className="sticky top-0 z-20 flex min-h-16 items-center justify-between gap-2 border-b bg-white/95 px-3 py-2 backdrop-blur md:px-8"><div className="flex min-w-0 items-center gap-2"><button type="button" aria-label="Toggle navigation menu" onClick={() => setMobileOpen((value) => !value)} className="relative grid size-10 shrink-0 place-items-center rounded-lg border bg-white md:hidden"><span className={cn("absolute h-0.5 w-5 bg-slate-700 transition duration-300", mobileOpen ? "rotate-45" : "-translate-y-1.5")} /><span className={cn("absolute h-0.5 w-5 bg-slate-700 transition", mobileOpen && "scale-x-0")} /><span className={cn("absolute h-0.5 w-5 bg-slate-700 transition duration-300", mobileOpen ? "-rotate-45" : "translate-y-1.5")} /></button><div className="min-w-0"><p className="truncate text-sm font-semibold">{session.tenant.name}</p><p className="truncate text-xs text-muted-foreground">All locations overview</p></div></div><div className="flex shrink-0 gap-1.5"><Button variant="outline" size="sm" className="size-9 px-0 sm:w-auto sm:px-3" aria-label="Profile" onClick={() => navigate(`/${tenantSlug}/profile`)}><UserCircle className="size-4 sm:mr-2" /><span className="hidden sm:inline">Profile</span></Button><Button variant="outline" size="sm" className="size-9 px-0 sm:w-auto sm:px-3" aria-label="Sign out" onClick={signOut}><LogOut className="size-4 sm:mr-2" /><span className="hidden sm:inline">Sign out</span></Button></div></header><main className="min-w-0 p-4 sm:p-5 md:p-8"><div className="mx-auto min-w-0 max-w-6xl"><Outlet /></div></main></div></div>;
}
