import { AuditLog } from "../models/AuditLog.js";
import { LabOrder } from "../models/LabOrder.js";
import { LabTest } from "../models/LabTest.js";
import { User } from "../models/User.js";
import { assertAllowedAttachment, signedClinicalAttachmentUrl, uploadLabReport } from "../services/s3AttachmentService.js";
import { notifyPatient, notifyStaffUsers } from "../services/staffNotificationService.js";
import { ApiError } from "../utils/ApiError.js";
import { asyncHandler } from "../utils/asyncHandler.js";

const scope = (req) => ({ tenantId: req.tenantId, locationId: req.locationId });
const clean = (value, label, max = 1000) => { const text = String(value || "").trim(); if (!text) throw new ApiError(400, `${label} is required`); if (text.length > max) throw new ApiError(400, `${label} is too long`); return text; };
const presentTest = (item) => ({ id: item._id, name: item.name, code: item.code, preparation: item.preparation, collectionDurationMinutes: item.collectionDurationMinutes, isActive: item.isActive });
const presentOrder = (item) => ({ id: item._id, test: { id: item.labTestId?._id || item.labTestId, name: item.testName, code: item.testCode, preparation: item.preparation }, status: item.status, scheduledAt: item.scheduledAt, patient: item.patientId?.name ? { id: item.patientId._id, name: item.patientId.name, phone: item.patientId.contact?.phone || "" } : undefined, labAttendant: item.labAttendantId?.name ? { id: item.labAttendantId._id, name: item.labAttendantId.name } : null, report: item.report ? { fileName: item.report.fileName, mimeType: item.report.mimeType, uploadedAt: item.report.uploadedAt } : null, createdAt: item.createdAt });

function populatedOrder(query, req) { return query.populate({ path: "patientId", select: "name contact", match: scope(req) }).populate({ path: "labAttendantId", select: "name", match: { ...scope(req), role: "lab_attendant" } }).populate({ path: "labTestId", select: "name code preparation" }); }

function validCollectionTime(value) {
  const date = new Date(value); if (Number.isNaN(date.getTime()) || date <= new Date()) throw new ApiError(400, "Choose a future collection time");
  const parts = new Intl.DateTimeFormat("en-GB", { timeZone: "Asia/Karachi", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).formatToParts(date); const hour = Number(parts.find((part) => part.type === "hour")?.value); const minute = Number(parts.find((part) => part.type === "minute")?.value);
  if (hour < 9 || hour >= 17 || ![0, 30].includes(minute)) throw new ApiError(400, "Lab collection times are available from 9:00 AM to 5:00 PM in 30-minute slots");
  return date;
}

async function assignBooking({ req, orderId, scheduledAt, patientId, actorPatientId = null }) {
  const when = validCollectionTime(scheduledAt);
  const filter = { _id: orderId, ...scope(req), status: "requested", ...(patientId ? { patientId } : {}) };
  const attendants = await User.find({ ...scope(req), role: "lab_attendant", isActive: { $ne: false } }).sort({ createdAt: 1 }).lean();
  if (!attendants.length) throw new ApiError(409, "No active Lab Attendant is configured for this branch");
  const occupiedAttendantIds = await LabOrder.distinct("labAttendantId", { ...scope(req), scheduledAt: when, status: { $in: ["booked", "arrived", "sample_collected"] } });
  const attendant = attendants.find((candidate) => !occupiedAttendantIds.some((id) => String(id) === String(candidate._id)));
  if (!attendant) throw new ApiError(409, "All Lab Attendants are already booked at this time. Please choose another slot.");
  try {
    const order = await LabOrder.findOneAndUpdate(filter, { $set: { status: "booked", scheduledAt: when, labAttendantId: attendant._id } }, { new: true, runValidators: true });
    if (!order) throw new ApiError(409, "This test is no longer available to book");
    await AuditLog.create({ ...scope(req), ...(actorPatientId ? { actorPatientId } : { actorUserId: req.user._id }), action: actorPatientId ? "patient_lab_collection_booked" : "lab_collection_booked", targetType: "LabOrder", targetId: order._id });
    await notifyStaffUsers({ ...scope(req), recipientUserIds: [attendant._id], type: "lab_collection_booked", title: "New lab collection booked", body: `A ${order.testName} collection is booked for ${when.toLocaleString("en-PK", { timeZone: "Asia/Karachi" })}.`, targetPath: "/lab-worklist", targetId: order._id });
    return order;
  } catch (error) { if (error?.code === 11000) throw new ApiError(409, "That Lab Attendant slot was just booked. Please choose another time."); throw error; }
}

export const listLabTests = asyncHandler(async (req, res) => { const tests = await LabTest.find({ ...scope(req), ...(req.user?.role === "admin" ? {} : { isActive: true }) }).sort({ name: 1 }).lean(); res.json({ success: true, data: { tests: tests.map(presentTest) } }); });
export const createLabTest = asyncHandler(async (req, res) => { const test = await LabTest.create({ ...scope(req), name: clean(req.body.name, "Test name", 160), code: clean(req.body.code, "Test code", 40).toUpperCase(), preparation: String(req.body.preparation || "No special preparation required.").trim().slice(0, 1000), collectionDurationMinutes: Number(req.body.collectionDurationMinutes || 30), createdBy: req.user._id }); await AuditLog.create({ ...scope(req), actorUserId: req.user._id, action: "lab_test_created", targetType: "LabTest", targetId: test._id }); res.status(201).json({ success: true, data: { test: presentTest(test) } }); });
export const updateLabTest = asyncHandler(async (req, res) => { const update = {}; if (Object.hasOwn(req.body, "isActive")) update.isActive = Boolean(req.body.isActive); if (Object.hasOwn(req.body, "preparation")) update.preparation = String(req.body.preparation || "").trim().slice(0, 1000); const test = await LabTest.findOneAndUpdate({ _id: req.params.id, ...scope(req) }, { $set: update }, { new: true, runValidators: true }); if (!test) throw new ApiError(404, "Lab test not found"); await AuditLog.create({ ...scope(req), actorUserId: req.user._id, action: "lab_test_updated", targetType: "LabTest", targetId: test._id }); res.json({ success: true, data: { test: presentTest(test) } }); });

export const listLabOrders = asyncHandler(async (req, res) => { const filter = { ...scope(req) }; if (req.user.role === "lab_attendant") filter.labAttendantId = req.user._id; const orders = await populatedOrder(LabOrder.find(filter).sort({ scheduledAt: 1, createdAt: -1 }), req).lean(); res.json({ success: true, data: { orders: orders.map(presentOrder) } }); });
export const bookLabOrder = asyncHandler(async (req, res) => { const order = await assignBooking({ req, orderId: req.params.id, scheduledAt: req.body.scheduledAt }); const populated = await populatedOrder(LabOrder.findById(order._id), req).lean(); res.json({ success: true, data: { order: presentOrder(populated) } }); });
export const updateLabOrderStatus = asyncHandler(async (req, res) => { const status = String(req.body.status || ""); if (!["arrived", "sample_collected", "no_show"].includes(status)) throw new ApiError(400, "Choose a valid lab collection status"); const allowedPrevious = { arrived: ["booked"], sample_collected: ["booked", "arrived"], no_show: ["booked", "arrived"] }; const order = await LabOrder.findOne({ _id: req.params.id, ...scope(req), labAttendantId: req.user._id, status: { $in: allowedPrevious[status] } }); if (!order) throw new ApiError(409, "This booking cannot be updated by this Lab Attendant"); order.status = status; if (status === "arrived") order.arrivedAt = new Date(); if (status === "sample_collected") order.collectedAt = new Date(); await order.save(); await AuditLog.create({ ...scope(req), actorUserId: req.user._id, action: `lab_${status}`, targetType: "LabOrder", targetId: order._id }); const populated = await populatedOrder(LabOrder.findById(order._id), req).lean(); res.json({ success: true, data: { order: presentOrder(populated) } }); });
export const uploadLabOrderReport = asyncHandler(async (req, res) => { assertAllowedAttachment(req.file); const order = await LabOrder.findOne({ _id: req.params.id, ...scope(req), labAttendantId: req.user._id, status: "sample_collected" }); if (!order) throw new ApiError(409, "A report can only be uploaded for a collected sample assigned to you"); const stored = await uploadLabReport({ file: req.file, labOrder: order, ...scope(req), patientId: order.patientId }); order.report = { ...stored, uploadedAt: new Date() }; order.reportUploadedBy = req.user._id; order.status = "report_available"; await order.save(); await AuditLog.create({ ...scope(req), actorUserId: req.user._id, action: "lab_report_uploaded", targetType: "LabOrder", targetId: order._id }); await notifyPatient({ ...scope(req), patientId: order.patientId, type: "patient_lab_report_available", title: "Your lab report is ready", body: `Your ${order.testName} report is now available in My Tests.`, targetPath: "/portal?view=tests", targetId: order._id }); const populated = await populatedOrder(LabOrder.findById(order._id), req).lean(); res.status(201).json({ success: true, data: { order: presentOrder(populated) } }); });
export const viewLabOrderReport = asyncHandler(async (req, res) => { const order = await LabOrder.findOne({ _id: req.params.id, ...scope(req), ...(req.user.role === "lab_attendant" ? { labAttendantId: req.user._id } : {}) }).lean(); if (!order?.report?.key) throw new ApiError(404, "Report not found"); await AuditLog.create({ ...scope(req), actorUserId: req.user._id, action: "lab_report_viewed", targetType: "LabOrder", targetId: order._id }); res.json({ success: true, data: { url: await signedClinicalAttachmentUrl(order.report.key) } }); });

export const patientPortalLabOrders = asyncHandler(async (req, res) => { const orders = await LabOrder.find({ tenantId: req.tenantId, locationId: req.locationId, patientId: req.portalPatient._id }).sort({ createdAt: -1 }).lean(); res.json({ success: true, data: { orders: orders.map(presentOrder) } }); });
export const patientPortalBookLabOrder = asyncHandler(async (req, res) => { const order = await assignBooking({ req, orderId: req.params.id, scheduledAt: req.body.scheduledAt, patientId: req.portalPatient._id, actorPatientId: req.portalPatient._id }); res.json({ success: true, data: { order: presentOrder(order) } }); });
export const patientPortalViewLabReport = asyncHandler(async (req, res) => { const order = await LabOrder.findOne({ _id: req.params.id, tenantId: req.tenantId, locationId: req.locationId, patientId: req.portalPatient._id, status: "report_available" }).lean(); if (!order?.report?.key) throw new ApiError(404, "Report not available"); await AuditLog.create({ tenantId: req.tenantId, locationId: req.locationId, actorPatientId: req.portalPatient._id, action: "patient_lab_report_viewed", targetType: "LabOrder", targetId: order._id }); res.json({ success: true, data: { url: await signedClinicalAttachmentUrl(order.report.key) } }); });
