import { AuditLog } from "../models/AuditLog.js";
import { Message } from "../models/Message.js";
import { MessageThread } from "../models/MessageThread.js";
import { Patient } from "../models/Patient.js";
import { Location } from "../models/Location.js";
import { ApiError } from "../utils/ApiError.js";
import { asyncHandler } from "../utils/asyncHandler.js";

const view = (message) => ({ id: message._id, senderType: message.senderType, senderId: message.senderId, body: message.body, sentAt: message.sentAt, readAt: message.readAt });
async function threadFor({ tenantId, locationId, patientId }) { return MessageThread.findOneAndUpdate({ tenantId, locationId, patientId }, { $setOnInsert: { tenantId, locationId, patientId, lastMessageAt: new Date() } }, { new: true, upsert: true }); }
async function conversation({ tenantId, locationId, patientId }) { const thread = await threadFor({ tenantId, locationId, patientId }); const messages = await Message.find({ tenantId, locationId, threadId: thread._id }).sort({ sentAt: 1 }).lean(); const location = await Location.findOne({ _id: locationId, tenantId }).select("schedulingSettings").lean(); return { thread: { id: thread._id, lastMessageAt: thread.lastMessageAt }, messages: messages.map(view), expectedResponseHours: location?.schedulingSettings?.patientMessageExpectedResponseHours ?? 24 }; }
async function send({ tenantId, locationId, patientId, senderType, senderId, body }) { const text = String(body || "").trim(); if (!text) throw new ApiError(400, "Write a message before sending"); if (text.length > 4000) throw new ApiError(400, "Message must be 4,000 characters or fewer"); const thread = await threadFor({ tenantId, locationId, patientId }); const message = await Message.create({ tenantId, locationId, patientId, threadId: thread._id, senderType, senderId, body: text, sentAt: new Date() }); await MessageThread.updateOne({ _id: thread._id }, { $set: { lastMessageAt: message.sentAt }, ...(senderType === "patient" ? { $set: { lastMessageAt: message.sentAt, escalationsSent: [] } } : { $set: { lastMessageAt: message.sentAt }, $pull: { escalationsSent: { $in: ["staff_due", "admin_flagged"] } } }) }); await AuditLog.create({ tenantId, locationId, ...(senderType === "patient" ? { actorPatientId: patientId } : { actorUserId: senderId }), action: senderType === "patient" ? "patient_message_sent" : "staff_message_sent", targetType: "MessageThread", targetId: thread._id }); return view(message); }
export const portalMessages = asyncHandler(async (req, res) => res.json({ success: true, data: await conversation({ tenantId: req.tenantId, locationId: req.locationId, patientId: req.portalPatient._id }) }));
export const portalSendMessage = asyncHandler(async (req, res) => { const message = await send({ tenantId: req.tenantId, locationId: req.locationId, patientId: req.portalPatient._id, senderType: "patient", senderId: req.portalPatient._id, body: req.body.body }); res.status(201).json({ success: true, data: { message } }); });
export const staffMessages = asyncHandler(async (req, res) => { const patient = await Patient.findOne({ _id: req.params.id, tenantId: req.tenantId, locationId: req.locationId }).lean(); if (!patient) throw new ApiError(404, "Patient not found in this location"); res.json({ success: true, data: await conversation({ tenantId: req.tenantId, locationId: req.locationId, patientId: patient._id }) }); });
export const staffSendMessage = asyncHandler(async (req, res) => { const patient = await Patient.findOne({ _id: req.params.id, tenantId: req.tenantId, locationId: req.locationId }).lean(); if (!patient) throw new ApiError(404, "Patient not found in this location"); const message = await send({ tenantId: req.tenantId, locationId: req.locationId, patientId: patient._id, senderType: "staff", senderId: req.user._id, body: req.body.body }); res.status(201).json({ success: true, data: { message } }); });
