import { Router } from "express";
import multer from "multer";
import { acceptAiSummary, addAmendment, finalizeEncounter, generateAiSummary, getEncounter, listPatientEncounters, startEncounter, updateDraft, uploadAttachment, removeAttachment, viewAttachment } from "../controllers/encounterController.js";
import { authenticate } from "../middleware/authenticate.js";
import { authorizeLocationAccess } from "../middleware/authorizeLocationAccess.js";
import { authorizeRoles } from "../middleware/authorizeRoles.js";
import { exportEncounter } from "../controllers/recordExportController.js";

export const encounterRouter = Router({ mergeParams: true });
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 10 * 1024 * 1024, files: 1 } });
encounterRouter.use(authenticate, authorizeLocationAccess);
encounterRouter.get("/:id/export", authorizeRoles("doctor", "admin"), exportEncounter);
encounterRouter.get("/:id/attachments/:attachmentId/view", authorizeRoles("doctor", "admin"), viewAttachment);
encounterRouter.use(authorizeRoles("doctor"));
encounterRouter.post("/", startEncounter);
encounterRouter.get("/patient/:patientId", listPatientEncounters);
encounterRouter.get("/:id", getEncounter);
encounterRouter.post("/:id/ai-summary", generateAiSummary);
encounterRouter.patch("/:id/ai-summary", acceptAiSummary);
encounterRouter.patch("/:id", updateDraft);
encounterRouter.patch("/:id/finalize", finalizeEncounter);
encounterRouter.post("/:id/amend", addAmendment);
encounterRouter.post("/:id/attachments", upload.single("file"), uploadAttachment);
encounterRouter.delete("/:id/attachments/:attachmentId", removeAttachment);
