import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, CalendarDays, ExternalLink, FileClock, FileText, HeartHandshake, History, LockKeyhole, Plus, Save, ShieldCheck, Stethoscope } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import { apiRequest, openPdfPreview } from "@/api/client";
import { CarePlanForm } from "@/components/CarePlanForm";
import { AiSummaryPanel } from "@/components/AiSummaryPanel";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useAuth } from "@/context/auth-context";
import { formatClinicDateTime } from "@/lib/schedule";

const emptyNotes = { symptoms: "", observations: "", diagnosis: "" };
const stamp = (value) => new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short", hour12: true }).format(new Date(value));

function HistoryPreview({ encounter, onClose }) {
  return <Dialog open={Boolean(encounter)} onOpenChange={(open) => { if (!open) onClose(); }}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>Past encounter reference</DialogTitle><DialogDescription>Read-only clinical context. Your current draft remains open underneath and is not changed.</DialogDescription></DialogHeader>{encounter && <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3 rounded-lg bg-slate-950 p-4 text-white"><div><p className="font-semibold">{encounter.appointmentId?.visitType || "Clinical encounter"}</p><p className="mt-1 text-xs text-slate-300">{stamp(encounter.finalizedAt)}</p></div><Badge className="bg-teal-400/15 text-teal-200">Finalized · read only</Badge></div><div className="grid gap-4">{[["Symptoms", encounter.notes?.symptoms], ["Observations", encounter.notes?.observations], ["Diagnosis", encounter.notes?.diagnosis]].map(([label, value]) => <section key={label} className="rounded-lg border bg-slate-50 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-800">{value || "Not documented"}</p></section>)}</div>{encounter.aiSummary?.text && <section className="rounded-lg border border-violet-200 bg-violet-50 p-4"><p className="text-sm font-semibold text-violet-950">Clinical Summary (AI-assisted)</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-700">{encounter.aiSummary.text}</p><div className="mt-3 flex flex-wrap gap-2 border-t border-violet-200 pt-3 text-xs text-muted-foreground"><span>Provider: Groq</span><span>·</span><span>Model: {encounter.aiSummary.model}</span><span>·</span><span>Accepted: {stamp(encounter.aiSummary.acceptedAt)}</span></div></section>}<section><p className="text-sm font-semibold">Amendments</p>{encounter.amendments?.length ? <div className="mt-3 space-y-2">{encounter.amendments.map((item) => <div key={item._id} className="rounded-lg border p-4"><p className="whitespace-pre-wrap text-sm">{item.text}</p><p className="mt-2 text-xs text-muted-foreground">{item.actor?.name || "Doctor"} · {stamp(item.timestamp)}</p></div>)}</div> : <p className="mt-2 rounded-md bg-slate-50 p-4 text-sm text-muted-foreground">No amendments.</p>}</section></div>}<DialogFooter><Button onClick={onClose}>Close reference</Button></DialogFooter></DialogContent></Dialog>;
}

export function EncounterPage() {
  const { tenantSlug, locationSlug, encounterId } = useParams(); const navigate = useNavigate(); const { session } = useAuth();
  const headers = useMemo(() => ({ Authorization: `Bearer ${session.accessToken}` }), [session.accessToken]); const root = `/${tenantSlug}/${locationSlug}`;
  const [encounter, setEncounter] = useState(null); const [notes, setNotes] = useState(emptyNotes); const [history, setHistory] = useState([]); const [carePlans, setCarePlans] = useState([]);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const [finalizeOpen, setFinalizeOpen] = useState(false); const [finalizing, setFinalizing] = useState(false); const [carePlanOpen, setCarePlanOpen] = useState(false);
  const [amendOpen, setAmendOpen] = useState(false); const [amendment, setAmendment] = useState(""); const [amending, setAmending] = useState(false);
  const [historyPreview, setHistoryPreview] = useState(null);
  const [exporting, setExporting] = useState(false);

  useEffect(() => { let active = true; async function load() { try { const data = await apiRequest(`${root}/encounters/${encounterId}`, { headers }); if (!active) return; setEncounter(data.encounter); setNotes(data.encounter.notes || emptyNotes); const [past, plans] = await Promise.all([apiRequest(`${root}/encounters/patient/${data.encounter.patientId._id}`, { headers }), data.encounter.status === "finalized" ? apiRequest(`${root}/careplans/patient/${data.encounter.patientId._id}`, { headers }) : Promise.resolve({ carePlans: [] })]); if (active) { setHistory(past.encounters.filter((item) => item._id !== encounterId)); setCarePlans(plans.carePlans.filter((plan) => String(plan.encounterId) === encounterId)); } } catch (requestError) { if (active) setError(requestError.message); } finally { if (active) setLoading(false); } } load(); return () => { active = false; }; }, [encounterId, headers, root]);

  async function saveDraft() { setSaving(true); setError(""); try { const data = await apiRequest(`${root}/encounters/${encounterId}`, { method: "PATCH", headers, body: JSON.stringify(notes) }); setEncounter(data.encounter); setNotes(data.encounter.notes); setMessage("Draft saved securely."); } catch (requestError) { setError(requestError.message); } finally { setSaving(false); } }
  function requestFinalize() { if (["symptoms", "observations", "diagnosis"].some((field) => !notes[field]?.trim())) return setError("Complete symptoms, observations, and diagnosis before finalizing."); setError(""); setFinalizeOpen(true); }
  async function finalize() { setFinalizing(true); setError(""); try { await apiRequest(`${root}/encounters/${encounterId}`, { method: "PATCH", headers, body: JSON.stringify(notes) }); const data = await apiRequest(`${root}/encounters/${encounterId}/finalize`, { method: "PATCH", headers }); setEncounter(data.encounter); setNotes(data.encounter.notes); setFinalizeOpen(false); setCarePlanOpen(true); setMessage("Encounter finalized and locked. Continue care by creating a care plan below."); } catch (requestError) { setError(requestError.message); setFinalizeOpen(false); } finally { setFinalizing(false); } }
  async function addAmendment(event) { event.preventDefault(); setAmending(true); setError(""); try { const data = await apiRequest(`${root}/encounters/${encounterId}/amend`, { method: "POST", headers, body: JSON.stringify({ text: amendment }) }); setEncounter(data.encounter); setAmendment(""); setAmendOpen(false); setMessage("Amendment appended without changing the original note."); } catch (requestError) { setError(requestError.message); } finally { setAmending(false); } }
  async function exportVisit() { setExporting(true); setError(""); try { await openPdfPreview(`${root}/encounters/${encounterId}/export`, session.accessToken); } catch (requestError) { setError(requestError.message); } finally { setExporting(false); } }

  if (loading) return <div className="h-96 animate-pulse rounded-xl bg-slate-100" />;
  if (!encounter) return <div className="rounded-md border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>;
  const finalized = encounter.status === "finalized";
  return <><Button variant="outline" size="sm" onClick={() => navigate(`/${tenantSlug}/${locationSlug}/${finalized ? "my-patients" : "queue"}`)}><ArrowLeft className="mr-2 size-4" /> Back to {finalized ? "My Patients" : "My Queue"}</Button>
    <section className="relative mt-5 overflow-hidden rounded-xl bg-slate-950 p-6 text-white shadow-panel"><div className="absolute inset-0 bg-[radial-gradient(circle_at_10%_10%,rgba(13,148,136,.32),transparent_34%)]" /><div className="relative flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><div className="flex items-center gap-2"><Badge className={finalized ? "bg-teal-400/15 text-teal-200" : "bg-amber-400/15 text-amber-200"}>{finalized ? <LockKeyhole className="mr-1 size-3.5" /> : <FileClock className="mr-1 size-3.5" />}{encounter.status}</Badge><span className="text-xs text-slate-400">Clinical encounter</span></div><h1 className="mt-3 text-3xl font-semibold">{encounter.patientId.name}</h1><div className="mt-3 flex flex-wrap gap-5 text-sm text-slate-300"><span className="flex items-center gap-2"><CalendarDays className="size-4 text-teal-300" />{formatClinicDateTime(encounter.appointmentId.scheduledAt)}</span><span className="flex items-center gap-2"><Stethoscope className="size-4 text-teal-300" />{encounter.appointmentId.visitType}</span></div></div>{finalized && <div className="flex flex-col items-end gap-3"><div className="rounded-lg border border-white/10 bg-white/5 px-4 py-3"><p className="text-xs uppercase text-slate-400">Finalized at</p><p className="mt-1 text-sm text-teal-200">{stamp(encounter.finalizedAt)}</p></div><Button variant="outline" className="border-white/20 bg-white/10 text-white hover:bg-white/20 hover:text-white" onClick={exportVisit} disabled={exporting}><ExternalLink className="mr-2 size-4" />{exporting ? "Preparing PDF..." : "Export this visit"}</Button></div>}</div></section>
    {error && <div className="mt-5 rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}{message && <div className="mt-5 flex items-center gap-2 rounded-md border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700"><ShieldCheck className="size-4" />{message}</div>}
    <Card className="mt-5 border-teal-200 bg-teal-50/60 shadow-none"><CardContent className="flex flex-col justify-between gap-4 p-4 sm:flex-row sm:items-center"><div><p className="font-semibold text-slate-900">Visit PDF export</p><p className="mt-1 text-sm text-slate-600">{finalized ? "Preview this finalized visit record in a new browser tab." : "Export becomes available after this encounter is finalized and locked."}</p></div><Button className="bg-teal-700 hover:bg-teal-800" onClick={exportVisit} disabled={!finalized || exporting}><ExternalLink className="mr-2 size-4" />{exporting ? "Preparing PDF..." : "Export this visit"}</Button></CardContent></Card>
    <AiSummaryPanel root={root} headers={headers} encounter={encounter} notes={notes} onAccepted={(updated) => { setEncounter(updated); setMessage("AI-assisted summary accepted after clinician review."); }} />
    <div className="mt-6 grid gap-6 xl:grid-cols-[1fr_320px]"><div className="space-y-6"><Card className={`bg-white shadow-none ${finalized ? "border-teal-200" : ""}`}><CardHeader><div className="flex items-start justify-between gap-4"><div className="flex gap-3"><div className={`grid size-10 place-items-center rounded-md ${finalized ? "bg-teal-50 text-teal-700" : "bg-amber-50 text-amber-700"}`}>{finalized ? <LockKeyhole className="size-5" /> : <FileText className="size-5" />}</div><div><CardTitle className="text-lg">Structured clinical note</CardTitle><CardDescription className="mt-1">{finalized ? "Original fields are locked. Add amendments separately." : "Finalize saves the latest text before locking it."}</CardDescription></div></div><Badge variant={encounter.status}>{encounter.status}</Badge></div></CardHeader><CardContent className="space-y-5">{[["symptoms", "Symptoms"], ["observations", "Observations"], ["diagnosis", "Diagnosis"]].map(([field, label]) => <div className="space-y-2" key={field}><Label>{label}</Label><Textarea className="min-h-32" value={notes[field] || ""} onChange={(event) => { setNotes((current) => ({ ...current, [field]: event.target.value })); setError(""); }} disabled={finalized} /></div>)}{!finalized && <div className="flex justify-end gap-3 border-t pt-5"><Button variant="outline" onClick={saveDraft} disabled={saving}><Save className="mr-2 size-4" />{saving ? "Saving…" : "Save Draft"}</Button><Button className="bg-teal-700 hover:bg-teal-800" onClick={requestFinalize}><LockKeyhole className="mr-2 size-4" /> Finalize Encounter</Button></div>}</CardContent></Card>
      {finalized && <Card className="border-teal-200 bg-gradient-to-br from-teal-50 to-white shadow-none"><CardHeader><div className="flex flex-col justify-between gap-4 sm:flex-row"><div className="flex gap-3"><div className="grid size-10 place-items-center rounded-md bg-teal-700 text-white"><HeartHandshake className="size-5" /></div><div><CardTitle className="text-lg">Continue with a care plan</CardTitle><CardDescription className="mt-1">Connect measurable follow-up care to this encounter.</CardDescription></div></div>{carePlans.length === 0 && <Button className="bg-teal-700 hover:bg-teal-800" onClick={() => setCarePlanOpen((value) => !value)}><Plus className="mr-2 size-4" /> Create Care Plan</Button>}</div></CardHeader><CardContent>{carePlans.length ? <div className="rounded-lg border border-emerald-200 bg-white p-4"><p className="font-medium">{carePlans[0].goal}</p><p className="mt-1 text-xs text-muted-foreground">Owner: {carePlans[0].owningCareTeamMemberId?.name}</p><Button variant="outline" size="sm" className="mt-3" onClick={() => navigate(`/${tenantSlug}/${locationSlug}/patients/${encounter.patientId._id}`)}>Open full care timeline</Button></div> : carePlanOpen ? <CarePlanForm root={root} headers={headers} encounterId={encounterId} onCreated={(plan) => { setCarePlans([plan]); setCarePlanOpen(false); setMessage("Care plan created and connected to this encounter."); }} /> : <p className="text-sm text-slate-600">Create now, or return through My Patients later.</p>}</CardContent></Card>}
      {finalized && <Card className="bg-white shadow-none"><CardHeader><div className="flex justify-between gap-4"><div><CardTitle className="text-lg">Amendment history</CardTitle><CardDescription className="mt-1">Append-only additions to the locked record.</CardDescription></div><Button variant="outline" onClick={() => setAmendOpen(true)}><Plus className="mr-2 size-4" /> Add Amendment</Button></div></CardHeader><CardContent>{encounter.amendments.length ? <div className="space-y-3">{encounter.amendments.map((item) => <div key={item._id} className="rounded-lg border bg-slate-50 p-4"><p className="whitespace-pre-wrap text-sm">{item.text}</p><p className="mt-2 text-xs text-muted-foreground">{item.actor?.name || "Doctor"} · {stamp(item.timestamp)}</p></div>)}</div> : <p className="rounded-md bg-slate-50 p-5 text-center text-sm text-muted-foreground">No amendments.</p>}</CardContent></Card>}</div>
      <aside><Card className="sticky top-6 bg-white shadow-none"><CardHeader><History className="size-5 text-violet-700" /><CardTitle className="text-lg">Patient history</CardTitle><CardDescription>Preview past finalized encounters without leaving or changing this draft.</CardDescription></CardHeader><CardContent>{history.length ? <div className="space-y-3">{history.map((item) => <button type="button" key={item._id} onClick={() => setHistoryPreview(item)} className="w-full rounded-md border p-3 text-left transition hover:border-violet-300 hover:bg-violet-50 focus:outline-none focus:ring-2 focus:ring-violet-300"><span className="flex items-center justify-between gap-2"><span className="text-sm font-medium">{item.appointmentId?.visitType}</span><span className="text-xs font-medium text-violet-700">View details</span></span><span className="mt-1 block text-xs text-muted-foreground">{stamp(item.finalizedAt)}</span><span className="mt-2 block line-clamp-2 text-xs">{item.notes.diagnosis}</span></button>)}</div> : <p className="text-sm text-muted-foreground">No previous encounters.</p>}</CardContent></Card></aside></div>
    <HistoryPreview encounter={historyPreview} onClose={() => setHistoryPreview(null)} />
    <Dialog open={finalizeOpen} onOpenChange={setFinalizeOpen}><DialogContent><DialogHeader><DialogTitle>Finalize this encounter?</DialogTitle><DialogDescription>Latest text will be saved first. The original note can only be amended afterward.</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={() => setFinalizeOpen(false)}>Keep draft</Button><Button className="bg-teal-700 hover:bg-teal-800" onClick={finalize} disabled={finalizing}>{finalizing ? "Saving and finalizing…" : "Save, finalize and lock"}</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={amendOpen} onOpenChange={setAmendOpen}><DialogContent><DialogHeader><DialogTitle>Add amendment</DialogTitle><DialogDescription>This appends without altering the original note.</DialogDescription></DialogHeader><form onSubmit={addAmendment}><Textarea className="min-h-36" value={amendment} onChange={(event) => setAmendment(event.target.value)} required /><DialogFooter className="mt-5"><Button type="button" variant="outline" onClick={() => setAmendOpen(false)}>Cancel</Button><Button type="submit" className="bg-teal-700 hover:bg-teal-800" disabled={amending}>{amending ? "Adding…" : "Add amendment"}</Button></DialogFooter></form></DialogContent></Dialog></>;
}
