import { useEffect, useMemo, useState } from "react";
import { CalendarPlus, FlaskConical } from "lucide-react";
import { useParams } from "react-router-dom";
import { apiRequest } from "@/api/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { useAuth } from "@/context/auth-context";
import { formatClinicDateTime } from "@/lib/schedule";
export function LabDeskPage() { const { tenantSlug, locationSlug } = useParams(); const { session } = useAuth(); const root=`/${tenantSlug}/${locationSlug}`; const headers=useMemo(()=>({Authorization:`Bearer ${session.accessToken}`}),[session.accessToken]); const [orders,setOrders]=useState([]),[selected,setSelected]=useState(null),[scheduledAt,setScheduledAt]=useState(""),[error,setError]=useState(""); const load=()=>apiRequest(`${root}/lab/orders`,{headers}).then(d=>setOrders(d.orders||[])).catch(e=>setError(e.message)); useEffect(()=>{load();},[root]); async function book(e){e.preventDefault();try{await apiRequest(`${root}/lab/orders/${selected.id}/book`,{method:"POST",headers,body:JSON.stringify({scheduledAt})});setSelected(null);setScheduledAt("");load();}catch(x){setError(x.message);}} return <div className="space-y-6"><div><p className="text-sm font-semibold text-teal-700">Front-desk operations</p><h1 className="mt-1 text-3xl font-bold">Lab Desk</h1><p className="mt-2 text-slate-600">Book patient sample collections. Payments are handled outside this workflow.</p></div>{error&&<p className="rounded-lg bg-red-50 p-3 text-red-800">{error}</p>}<Card><CardHeader><CardTitle>Requested tests</CardTitle><CardDescription>Book every requested test at a suitable lab collection time.</CardDescription></CardHeader><CardContent><div className="space-y-3">{orders.length?orders.map(o=><div key={o.id} className="flex flex-col justify-between gap-3 rounded-lg border p-4 sm:flex-row sm:items-center"><div><p className="font-semibold">{o.patient?.name} · {o.test.name}</p><p className="mt-1 text-sm text-slate-600">{o.status.replaceAll("_"," ")} {o.scheduledAt?`· ${formatClinicDateTime(o.scheduledAt)}`:""}</p><p className="mt-1 text-xs text-slate-500">{o.test.preparation}</p></div>{o.status==="requested"&&<Button className="bg-teal-700" onClick={()=>setSelected(o)}><CalendarPlus className="mr-2 size-4"/>Book collection</Button>}</div>):<p className="p-8 text-center text-slate-500">No lab orders.</p>}</div></CardContent></Card><Dialog open={Boolean(selected)} onOpenChange={v=>!v&&setSelected(null)}><DialogContent><DialogHeader><DialogTitle>Book lab collection</DialogTitle></DialogHeader><form className="space-y-4" onSubmit={book}><p className="rounded-lg bg-slate-50 p-3 text-sm"><b>{selected?.patient?.name}</b><br/>{selected?.test.name}</p><Input type="datetime-local" value={scheduledAt} onChange={e=>setScheduledAt(e.target.value)} required/><p className="text-xs text-slate-500">Available collection times are 9:00 AM–5:00 PM in 30-minute slots.</p><DialogFooter><Button className="bg-teal-700">Confirm booking</Button></DialogFooter></form></DialogContent></Dialog></div>; }
