import { useEffect, useMemo, useState } from "react";
import { FlaskConical, Plus } from "lucide-react";
import { useParams } from "react-router-dom";
import { apiRequest } from "@/api/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useAuth } from "@/context/auth-context";

export function LabSetupPage() {
  const { tenantSlug, locationSlug } = useParams(); const { session } = useAuth(); const root = `/${tenantSlug}/${locationSlug}`; const headers = useMemo(() => ({ Authorization: `Bearer ${session.accessToken}` }), [session.accessToken]);
  const [tests, setTests] = useState([]); const [form, setForm] = useState({ name: "", code: "", preparation: "", collectionDurationMinutes: 30 }); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = () => apiRequest(`${root}/lab/tests`, { headers }).then((data) => setTests(data.tests || [])).catch((e) => setError(e.message)); useEffect(() => { load(); }, [root]);
  async function submit(event) { event.preventDefault(); setError(""); try { const data = await apiRequest(`${root}/lab/tests`, { method: "POST", headers, body: JSON.stringify(form) }); setTests((current) => [...current, data.test].sort((a, b) => a.name.localeCompare(b.name))); setForm({ name: "", code: "", preparation: "", collectionDurationMinutes: 30 }); setNotice("Lab test is now available for Doctors to request."); } catch (e) { setError(e.message); } }
  async function toggle(test) { try { const data = await apiRequest(`${root}/lab/tests/${test.id}`, { method: "PATCH", headers, body: JSON.stringify({ isActive: !test.isActive }) }); setTests((current) => current.map((item) => item.id === data.test.id ? data.test : item)); } catch (e) { setError(e.message); } }
  return <div className="mx-auto max-w-5xl space-y-6"><div><p className="text-sm font-semibold text-teal-700">Clinic administration</p><h1 className="mt-1 text-3xl font-bold">Lab setup</h1><p className="mt-2 text-slate-600">Manage tests patients can request after a Doctor orders them. Payments are not tracked here.</p></div>{notice && <p className="rounded-lg bg-emerald-50 p-3 text-emerald-800">{notice}</p>}{error && <p className="rounded-lg bg-red-50 p-3 text-red-800">{error}</p>}<div className="grid gap-6 lg:grid-cols-[380px_1fr]"><Card><CardHeader><CardTitle>Add lab test</CardTitle><CardDescription>Use a clear name patients will recognise.</CardDescription></CardHeader><CardContent><form className="space-y-4" onSubmit={submit}><label><Label>Test name</Label><Input className="mt-2" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Complete blood count" required /></label><label><Label>Short code</Label><Input className="mt-2" value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value })} placeholder="CBC" required /></label><label><Label>Preparation instructions</Label><Textarea className="mt-2" value={form.preparation} onChange={(e) => setForm({ ...form, preparation: e.target.value })} placeholder="e.g. No fasting required" /></label><label><Label>Collection duration (minutes)</Label><Input className="mt-2" type="number" min="15" step="15" value={form.collectionDurationMinutes} onChange={(e) => setForm({ ...form, collectionDurationMinutes: e.target.value })} required /></label><Button className="w-full bg-teal-700 hover:bg-teal-800"><Plus className="mr-2 size-4" />Add test</Button></form></CardContent></Card><Card><CardHeader><CardTitle>Available tests</CardTitle><CardDescription>Inactive tests remain in historical orders but cannot be newly requested.</CardDescription></CardHeader><CardContent><div className="space-y-3">{tests.length ? tests.map((test) => <div key={test.id} className="flex items-center justify-between gap-3 rounded-lg border p-4"><div><p className="font-semibold">{test.name} <span className="text-sm font-normal text-slate-500">({test.code})</span></p><p className="mt-1 text-sm text-slate-600">{test.preparation}</p></div><Button size="sm" variant="outline" onClick={() => toggle(test)}>{test.isActive ? "Deactivate" : "Activate"}</Button></div>) : <div className="rounded-lg border border-dashed p-8 text-center text-slate-500"><FlaskConical className="mx-auto size-8" />No lab tests yet.</div>}</div></CardContent></Card></div></div>;
}
