import { useEffect, useMemo, useState } from "react";
import { Activity, ArrowLeft, PhoneCall } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import { apiRequest } from "@/api/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { useAuth } from "@/context/auth-context";
import { useRealtimeRevision } from "@/realtime/useRealtimeRevision";

export function MonitoringAdherencePage() { const { tenantSlug, locationSlug } = useParams(); const { session } = useAuth(); const navigate = useNavigate(); const root = `/${tenantSlug}/${locationSlug}`; const headers = useMemo(() => ({ Authorization: `Bearer ${session.accessToken}` }), [session.accessToken]); const revision = useRealtimeRevision(["monitoringreading:created", "monitoringenrollment:updated"]); const [items, setItems] = useState([]); const [error, setError] = useState(""); const [creating, setCreating] = useState(""); useEffect(() => { apiRequest(`${root}/monitoring/adherence`, { headers }).then((data) => setItems(data.enrollments || [])).catch((e) => setError(e.message)); }, [headers, revision, root]); async function task(item) { setCreating(item.id); try { await apiRequest(`${root}/monitoring/enrollments/${item.id}/outreach-task`, { method: "POST", headers }); setItems((current) => current.filter((entry) => entry.id !== item.id)); } catch (e) { setError(e.message); } finally { setCreating(""); } } return <><Button size="sm" variant="outline" onClick={() => navigate(`${root}/dashboard`)}><ArrowLeft className="mr-2 size-4" />Back</Button><div className="mt-5"><p className="text-sm font-medium text-teal-700">Care coordination</p><h1 className="mt-1 flex items-center gap-2 text-3xl font-semibold"><Activity className="size-7 text-teal-700" />Monitoring adherence</h1><p className="mt-2 text-muted-foreground">Patients with no recent manual readings. This identifies outreach needs only; it makes no clinical conclusion.</p></div>{error && <p className="mt-5 rounded-md bg-red-50 p-3 text-sm text-red-700">{error}</p>}<Card className="mt-6 bg-white shadow-none"><CardHeader><CardTitle>Needs outreach</CardTitle><CardDescription>{items.length} active monitoring enrollment{items.length === 1 ? "" : "s"} with poor adherence.</CardDescription></CardHeader><CardContent className="space-y-3">{items.length ? items.map((item) => <div className="flex flex-col justify-between gap-3 rounded-xl border p-4 sm:flex-row sm:items-center" key={item.id}><div><p className="font-semibold">{item.patient?.name || "Patient"}</p><p className="mt-1 text-sm text-slate-600">{item.typeLabel} · {item.daysSinceLastReading} days since last reading</p></div><Button className="bg-teal-700" disabled={creating === item.id} onClick={() => task(item)}><PhoneCall className="mr-2 size-4" />{creating === item.id ? "Creating…" : "Create Outreach Task"}</Button></div>) : <p className="rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground">No adherence outreach is currently needed.</p>}</CardContent></Card></>; }
