import { createElement, useEffect, useMemo, useState } from "react";
import { Activity, ArrowRight, CalendarClock, CalendarDays, CalendarPlus2, CheckCircle2, ClipboardCheck, MessageSquareText, PhoneCall, PhoneOff, ThumbsDown, UserRound } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import { apiRequest } from "@/api/client";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { useAuth } from "@/context/auth-context";

const dateLabel = (value) => new Intl.DateTimeFormat("en-PK", { dateStyle: "medium" }).format(new Date(value));
const outcomeLabels = { agreed: "Agreed to follow-up", declined: "Declined", unreachable: "Unreachable" };

export function MyTasksPage() {
  const { tenantSlug, locationSlug } = useParams(); const { session } = useAuth();
  const navigate = useNavigate();
  const headers = useMemo(() => ({ Authorization: `Bearer ${session.accessToken}` }), [session.accessToken]); const root = `/${tenantSlug}/${locationSlug}`;
  const [tasks, setTasks] = useState([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const [selectedTask, setSelectedTask] = useState(null); const [outcomeNote, setOutcomeNote] = useState(""); const [completing, setCompleting] = useState(false);
  const [activeOutreachId, setActiveOutreachId] = useState(""); const [outreachForm, setOutreachForm] = useState({ timeframe: "", note: "" }); const [outreachError, setOutreachError] = useState(""); const [recordingId, setRecordingId] = useState("");
  useEffect(() => { apiRequest(`${root}/tasks?assignedToUserId=me`, { headers }).then((data) => setTasks(data.tasks)).catch((requestError) => setError(requestError.message)).finally(() => setLoading(false)); }, [headers, root]);
  function requestComplete(task) { setSelectedTask(task); setOutcomeNote(""); setError(""); }
  async function complete() { setCompleting(true); setError(""); try { const data = await apiRequest(`${root}/tasks/${selectedTask._id}/complete`, { method: "PATCH", headers, body: JSON.stringify({ outcomeNote }) }); setTasks((current) => current.map((task) => task._id === selectedTask._id ? data.task : task)); setSelectedTask(null); setOutcomeNote(""); } catch (requestError) { setError(requestError.message); } finally { setCompleting(false); } }
  function beginAgreed(task) { setActiveOutreachId(task._id); setOutreachForm({ timeframe: "", note: "" }); setOutreachError(""); }
  async function recordOutcome(task, outcome, values = {}) {
    if (outcome === "agreed" && !values.note?.trim()) { setOutreachError("Add a coordinator note before creating the recall request."); return; }
    if (outcome === "agreed" && !values.timeframe) { setOutreachError("Select when the patient would like to return."); return; }
    setRecordingId(task._id); setOutreachError(""); setError("");
    try {
      const data = await apiRequest(`${root}/tasks/${task._id}/outcome`, { method: "PATCH", headers, body: JSON.stringify({ outcome, ...values }) });
      setTasks((current) => current.map((item) => item._id === task._id ? data.task : item));
      setActiveOutreachId(""); setOutreachForm({ timeframe: "", note: "" });
    } catch (requestError) { if (outcome === "agreed") setOutreachError(requestError.message); else setError(requestError.message); }
    finally { setRecordingId(""); }
  }

  const openTasks = tasks.filter((task) => task.status === "open");
  const outreachTasks = openTasks.filter((task) => task.type === "outreach");
  const overdueTasks = openTasks.filter((task) => new Date(task.dueDate) < new Date(new Date().toDateString()));
  const completedTasks = tasks.filter((task) => task.status === "completed");

  return <><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-teal-700">Care coordination workspace</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Welcome, {session.user.name}</h1><p className="mt-2 text-muted-foreground">Prioritized care-plan work and patient outreach assigned to you in this branch.</p></div><div className="relative overflow-hidden rounded-xl border border-teal-100 bg-gradient-to-br from-white to-teal-50 px-5 py-3.5 shadow-sm sm:mb-1 sm:min-w-56"><div className="absolute -right-5 -top-6 size-20 rounded-full bg-teal-100/60" /><div className="relative flex items-center gap-3"><span className="grid size-10 place-items-center rounded-lg bg-teal-700 text-white shadow-sm"><CalendarDays className="size-5" /></span><div><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-teal-700">Today</p><p className="mt-0.5 text-sm font-semibold text-slate-900">{new Intl.DateTimeFormat("en-PK", { weekday: "long", day: "numeric", month: "long" }).format(new Date())}</p></div></div></div></div>{error && <div className="mt-6 rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    {loading ? <div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[1, 2, 3, 4].map((item) => <div key={item} className="h-32 animate-pulse rounded-xl border bg-white" />)}</div> : <><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[
      ["Open tasks", openTasks.length, "Work requiring action", ClipboardCheck, "bg-teal-50 text-teal-700"],
      ["Patient outreach", outreachTasks.length, "Calls awaiting an outcome", PhoneCall, "bg-violet-50 text-violet-700"],
      ["Overdue", overdueTasks.length, "Past their assigned due date", CalendarClock, "bg-amber-50 text-amber-700"],
      ["Completed", completedTasks.length, "Progress recorded to date", CheckCircle2, "bg-emerald-50 text-emerald-700"],
    ].map(([label, value, detail, icon, tone]) => <Card key={label} className="bg-white shadow-none"><CardContent className="p-5"><div className="flex items-start justify-between"><div><p className="text-sm font-medium text-slate-600">{label}</p><p className="mt-2 text-3xl font-semibold">{value}</p></div><span className={`grid size-10 place-items-center rounded-lg ${tone}`}>{createElement(icon, { className: "size-5" })}</span></div><p className="mt-4 border-t pt-3 text-xs text-muted-foreground">{detail}</p></CardContent></Card>)}</div>
      <Card className="mt-5 border-teal-100 bg-gradient-to-r from-teal-50/70 to-white shadow-none"><CardContent className="flex flex-col justify-between gap-4 p-4 sm:flex-row sm:items-center"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-lg bg-white text-teal-700 shadow-sm"><Activity className="size-5" /></span><div><p className="text-sm font-semibold">Track the plans behind your work</p><p className="mt-0.5 text-xs text-muted-foreground">Review targets, cadence, progress history and linked task outcomes.</p></div></div><Button variant="outline" className="bg-white" onClick={() => navigate(`/${tenantSlug}/${locationSlug}/my-care-plans`)}>My Care Plans <ArrowRight className="ml-2 size-4" /></Button></CardContent></Card></>}
    <Card className="mt-8 bg-white shadow-none"><CardContent className="p-0">{tasks.length === 0 ? <div className="grid place-items-center px-6 py-16 text-center"><ClipboardCheck className="size-7 text-slate-400" /><p className="mt-3 font-medium">No assigned tasks</p><p className="mt-1 text-sm text-muted-foreground">New care-plan actions will appear here.</p></div> : <div className="divide-y">{tasks.map((task) => { const outreach = task.type === "outreach"; const overdue = task.status === "open" && new Date(task.dueDate) < new Date(new Date().toDateString()); const expanded = activeOutreachId === task._id; return <article key={task._id} className={`p-5 ${overdue ? "bg-red-50/60" : ""}`}><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-start"><div className="flex min-w-0 gap-3"><span className={`grid size-10 shrink-0 place-items-center rounded-md ${overdue ? "bg-red-100 text-red-700" : outreach ? "bg-violet-50 text-violet-700" : "bg-teal-50 text-teal-700"}`}>{outreach ? <PhoneCall className="size-5" /> : <CalendarClock className="size-5" />}</span><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{task.description}</p><Badge variant={task.status}>{task.status}</Badge>{outreach && <Badge className="border-violet-200 bg-violet-50 text-violet-700">patient outreach</Badge>}{overdue && <Badge variant="cancelled">overdue</Badge>}</div><p className="mt-1 flex items-center gap-1.5 text-xs text-muted-foreground"><UserRound className="size-3.5" />{task.carePlanId?.patientId?.name || "Patient"} · {task.carePlanId?.goal}</p><p className={`mt-1 text-xs ${overdue ? "font-semibold text-red-700" : "text-muted-foreground"}`}>Due {dateLabel(task.dueDate)}</p>{task.status === "completed" && outreach && <p className="mt-2 text-xs font-medium text-slate-600">Outcome: <span className="text-teal-700">{outcomeLabels[task.outcome] || task.outcome}</span></p>}{task.status === "completed" && task.outcomeNote && <p className="mt-3 flex items-start gap-2 rounded-md bg-slate-50 p-3 text-xs leading-5 text-slate-600"><MessageSquareText className="mt-0.5 size-3.5 shrink-0 text-teal-700" /><span><span className="font-medium text-slate-700">Note:</span> {task.outcomeNote} — completed by {task.assignedToUserId?.name || session.user.name}, {dateLabel(task.completedAt)}</span></p>}</div></div>
          {task.status === "open" && !outreach && <Button size="sm" className="bg-teal-700 hover:bg-teal-800" onClick={() => requestComplete(task)}><CheckCircle2 className="mr-2 size-4" /> Mark Complete</Button>}
          {task.status === "open" && outreach && <div className="flex flex-wrap gap-2"><Button size="sm" className="bg-teal-700 hover:bg-teal-800" onClick={() => beginAgreed(task)}><CheckCircle2 className="mr-2 size-4" /> Agreed to follow-up</Button><Button size="sm" variant="outline" onClick={() => recordOutcome(task, "declined")} disabled={recordingId === task._id}><ThumbsDown className="mr-2 size-4" /> Declined</Button><Button size="sm" variant="outline" onClick={() => recordOutcome(task, "unreachable")} disabled={recordingId === task._id}><PhoneOff className="mr-2 size-4" /> Unreachable</Button></div>}
        </div>{expanded && <div className="ml-0 mt-5 rounded-xl border border-teal-200 bg-teal-50/60 p-4 sm:ml-[52px]"><div className="flex items-start gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-lg bg-white text-teal-700"><CalendarPlus2 className="size-4" /></span><div><p className="text-sm font-semibold text-teal-950">Create recall request</p><p className="mt-1 text-xs text-teal-800">Record the agreed timeframe and hand scheduling to Front-desk.</p></div></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>Follow-up timeframe</Label><Select value={outreachForm.timeframe} onValueChange={(value) => { setOutreachForm((current) => ({ ...current, timeframe: value })); setOutreachError(""); }}><SelectTrigger className="bg-white"><SelectValue placeholder="Select timeframe" /></SelectTrigger><SelectContent><SelectItem value="1_week">Within 1 week</SelectItem><SelectItem value="2_weeks">Within 2 weeks</SelectItem><SelectItem value="1_month">Within 1 month</SelectItem></SelectContent></Select></div><div className="space-y-2 sm:col-span-2"><Label>Coordinator note <span className="text-red-600">*</span></Label><Textarea className="min-h-24 bg-white" value={outreachForm.note} onChange={(event) => { setOutreachForm((current) => ({ ...current, note: event.target.value })); setOutreachError(""); }} placeholder="What was agreed with the patient? Include useful scheduling context." maxLength={5000} /></div></div>{outreachError && <p className="mt-3 text-sm text-red-700">{outreachError}</p>}<div className="mt-4 flex justify-end gap-2"><Button size="sm" variant="outline" onClick={() => setActiveOutreachId("")}>Cancel</Button><Button size="sm" className="bg-teal-700 hover:bg-teal-800" onClick={() => recordOutcome(task, "agreed", outreachForm)} disabled={recordingId === task._id}>{recordingId === task._id ? "Creating…" : "Create recall request"}</Button></div></div>}</article>; })}</div>}</CardContent></Card>
    <Dialog open={Boolean(selectedTask)} onOpenChange={(next) => { if (!next && !completing) setSelectedTask(null); }}><DialogContent><DialogHeader><div className="mb-2 grid size-11 place-items-center rounded-md bg-teal-50 text-teal-700"><CheckCircle2 className="size-5" /></div><DialogTitle>Complete this task?</DialogTitle><DialogDescription>Record what happened so the care-plan owner can understand the patient's progress.</DialogDescription></DialogHeader><div className="space-y-2"><Label htmlFor="outcome-note">Outcome notes <span className="font-normal text-muted-foreground">(optional)</span></Label><Textarea id="outcome-note" className="min-h-28" value={outcomeNote} onChange={(event) => setOutcomeNote(event.target.value)} placeholder="e.g. BP recorded as 128/82; patient confirmed medication adherence." maxLength={5000} /></div><DialogFooter><Button variant="outline" onClick={() => setSelectedTask(null)} disabled={completing}>Cancel</Button><Button className="bg-teal-700 hover:bg-teal-800" onClick={complete} disabled={completing}>{completing ? "Completing…" : "Confirm completion"}</Button></DialogFooter></DialogContent></Dialog>
  </>;
}
