import { useEffect, useMemo, useState } from "react";
import { CalendarClock, CheckCircle2, ClipboardCheck, MessageSquareText, UserRound } from "lucide-react";
import { useParams } from "react-router-dom";
import { apiRequest } from "@/api/client";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useAuth } from "@/context/auth-context";

const dateLabel = (value) => new Intl.DateTimeFormat("en-PK", { dateStyle: "medium" }).format(new Date(value));
export function MyTasksPage() {
  const { tenantSlug, locationSlug } = useParams(); const { session } = useAuth();
  const headers = useMemo(() => ({ Authorization: `Bearer ${session.accessToken}` }), [session.accessToken]); const root = `/${tenantSlug}/${locationSlug}`;
  const [tasks, setTasks] = useState([]); const [error, setError] = useState(""); const [selectedTask, setSelectedTask] = useState(null); const [outcomeNote, setOutcomeNote] = useState(""); const [completing, setCompleting] = useState(false);
  useEffect(() => { apiRequest(`${root}/tasks?assignedToUserId=me`, { headers }).then((data) => setTasks(data.tasks)).catch((requestError) => setError(requestError.message)); }, [headers, root]);
  function requestComplete(task) { setSelectedTask(task); setOutcomeNote(""); setError(""); }
  async function complete() { setCompleting(true); setError(""); try { const data = await apiRequest(`${root}/tasks/${selectedTask._id}/complete`, { method: "PATCH", headers, body: JSON.stringify({ outcomeNote }) }); setTasks((current) => current.map((task) => task._id === selectedTask._id ? data.task : task)); setSelectedTask(null); setOutcomeNote(""); } catch (requestError) { setError(requestError.message); } finally { setCompleting(false); } }
  return <><p className="text-sm font-medium text-teal-700">Care coordination</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">My Tasks</h1><p className="mt-2 text-muted-foreground">Prioritized follow-ups assigned to you in this branch.</p>{error && <div className="mt-6 rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}<Card className="mt-8 bg-white shadow-none"><CardContent className="p-0">{tasks.length === 0 ? <div className="grid place-items-center px-6 py-16 text-center"><ClipboardCheck className="size-7 text-slate-400" /><p className="mt-3 font-medium">No assigned tasks</p><p className="mt-1 text-sm text-muted-foreground">New care-plan actions will appear here.</p></div> : <div className="divide-y">{tasks.map((task) => { const overdue = task.status === "open" && new Date(task.dueDate) < new Date(new Date().toDateString()); return <article key={task._id} className={`p-5 ${overdue ? "bg-red-50/60" : ""}`}><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div className="flex gap-3"><span className={`grid size-10 shrink-0 place-items-center rounded-md ${overdue ? "bg-red-100 text-red-700" : "bg-teal-50 text-teal-700"}`}><CalendarClock className="size-5" /></span><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{task.description}</p><Badge variant={task.status}>{task.status}</Badge>{overdue && <Badge variant="cancelled">overdue</Badge>}</div><p className="mt-1 flex items-center gap-1.5 text-xs text-muted-foreground"><UserRound className="size-3.5" />{task.carePlanId?.patientId?.name || "Patient"} · {task.carePlanId?.goal}</p><p className={`mt-1 text-xs ${overdue ? "font-semibold text-red-700" : "text-muted-foreground"}`}>Due {dateLabel(task.dueDate)}</p>{task.status === "completed" && task.outcomeNote && <p className="mt-3 flex items-start gap-2 rounded-md bg-slate-50 p-3 text-xs leading-5 text-slate-600"><MessageSquareText className="mt-0.5 size-3.5 shrink-0 text-teal-700" /><span><span className="font-medium text-slate-700">Note:</span> {task.outcomeNote} — completed by {task.assignedToUserId?.name || session.user.name}, {dateLabel(task.completedAt)}</span></p>}</div></div>{task.status === "open" && <Button size="sm" className="bg-teal-700 hover:bg-teal-800" onClick={() => requestComplete(task)}><CheckCircle2 className="mr-2 size-4" /> Mark Complete</Button>}</div></article>; })}</div>}</CardContent></Card>
    <Dialog open={Boolean(selectedTask)} onOpenChange={(next) => { if (!next && !completing) setSelectedTask(null); }}><DialogContent><DialogHeader><div className="mb-2 grid size-11 place-items-center rounded-md bg-teal-50 text-teal-700"><CheckCircle2 className="size-5" /></div><DialogTitle>Complete this task?</DialogTitle><DialogDescription>Record what happened so the care-plan owner can understand the patient's progress.</DialogDescription></DialogHeader><div className="space-y-2"><Label htmlFor="outcome-note">Outcome notes <span className="font-normal text-muted-foreground">(optional)</span></Label><Textarea id="outcome-note" className="min-h-28" value={outcomeNote} onChange={(event) => setOutcomeNote(event.target.value)} placeholder="e.g. BP recorded as 128/82; patient confirmed medication adherence." maxLength={5000} /></div><DialogFooter><Button variant="outline" onClick={() => setSelectedTask(null)} disabled={completing}>Cancel</Button><Button className="bg-teal-700 hover:bg-teal-800" onClick={complete} disabled={completing}>{completing ? "Completing…" : "Confirm completion"}</Button></DialogFooter></DialogContent></Dialog>
  </>;
}
