import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, CalendarDays, ChevronDown, ChevronUp, ExternalLink, FileText, HeartHandshake, History, MapPin, Phone, ShieldCheck, UserRound } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import { apiRequest, openPdfPreview } from "@/api/client";
import { TaskForm } from "@/components/TaskForm";
import { TaskOutcome } from "@/components/TaskOutcome";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { useAuth } from "@/context/auth-context";
import { formatClinicDateTime } from "@/lib/schedule";

const day = (value) => new Intl.DateTimeFormat("en-PK", { dateStyle: "medium" }).format(new Date(value));

function TaskList({ tasks }) {
  if (!tasks.length) return <p className="rounded-md bg-slate-50 p-4 text-sm text-muted-foreground">No tasks assigned.</p>;
  return <div className="space-y-2">{tasks.map((task) => <div key={task._id} className="rounded-lg border p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-medium">{task.description}</p><p className="mt-1 text-xs text-muted-foreground">{task.assignedToUserId?.name} · Due {day(task.dueDate)}</p></div><Badge variant={task.status}>{task.status}</Badge></div><TaskOutcome task={task} /></div>)}</div>;
}

function EncounterTimeline({ encounters, onOpen, onExport, exportingId, administrativeOnly = false }) {
  if (!encounters.length) return <p className="text-sm text-muted-foreground">No encounters.</p>;
  return <div className="space-y-3">{encounters.map((item) => <div key={item._id} className="rounded-lg border p-4"><div className="flex justify-between gap-3"><div><p className="font-medium">{item.appointmentId?.visitType || "Clinical encounter"}</p><p className="mt-1 text-xs text-muted-foreground">{item.appointmentId?.scheduledAt ? formatClinicDateTime(item.appointmentId.scheduledAt) : day(item.createdAt)} · {item.doctorId?.name || "Doctor unavailable"}</p></div><Badge variant={item.status}>{item.status}</Badge></div>{!administrativeOnly && <><p className="mt-2 text-sm text-slate-600">{item.notes?.diagnosis || "Diagnosis pending"}</p>{item.aiSummary?.text && <div className="mt-3 rounded-md border border-violet-200 bg-violet-50 p-3"><p className="text-xs font-semibold text-violet-900">Clinical Summary (AI-assisted)</p><p className="mt-1 text-xs leading-5 text-slate-600">{item.aiSummary.text}</p><p className="mt-2 text-[11px] text-muted-foreground">Groq · {item.aiSummary.model} · Clinician accepted {day(item.aiSummary.acceptedAt)}</p></div>}{item.amendments?.length > 0 && <p className="mt-2 flex items-center gap-1 text-xs text-muted-foreground"><History className="size-3.5" />{item.amendments.length} amendment{item.amendments.length === 1 ? "" : "s"}</p>}{item.status === "finalized" && <div className="mt-3 flex flex-wrap gap-2">{onOpen && <Button size="sm" variant="outline" onClick={() => onOpen(item._id)}>Open encounter & amendments</Button>}{onExport && <Button size="sm" className="bg-teal-700 hover:bg-teal-800" onClick={() => onExport(item._id)} disabled={exportingId === item._id}><ExternalLink className="mr-2 size-4" />{exportingId === item._id ? "Preparing PDF..." : "Export visit PDF"}</Button>}</div>}</>}</div>)}</div>;
}

export function PatientProfilePage() {
  const { tenantSlug, locationSlug, patientId } = useParams(); const navigate = useNavigate(); const { session } = useAuth();
  const headers = useMemo(() => ({ Authorization: `Bearer ${session.accessToken}` }), [session.accessToken]); const root = `/${tenantSlug}/${locationSlug}`;
  const [record, setRecord] = useState(null); const [carePlans, setCarePlans] = useState([]); const [expanded, setExpanded] = useState(""); const [taskPlan, setTaskPlan] = useState(""); const [error, setError] = useState("");
  const [exporting, setExporting] = useState(false);
  const [exportingEncounterId, setExportingEncounterId] = useState("");
  useEffect(() => { let active = true; Promise.all([apiRequest(`${root}/patients/${patientId}`, { headers }), apiRequest(`${root}/careplans/patient/${patientId}`, { headers })]).then(([patientData, planData]) => { if (active) { setRecord(patientData); setCarePlans(planData.carePlans); } }).catch((requestError) => { if (active) setError(requestError.message); }); return () => { active = false; }; }, [headers, patientId, root]);
  if (error) return <div className="rounded-md border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>;
  if (!record) return <div className="h-64 animate-pulse rounded-xl bg-slate-100" />;
  const { patient, appointments, encounters } = record;
  const backPath = session.user.role === "doctor" ? `${root}/my-patients` : session.user.role === "frontdesk" ? `${root}/patients` : `${root}/my-care-plans`;
  function addTask(planId, task) { setCarePlans((current) => current.map((plan) => plan._id === planId ? { ...plan, tasks: [...plan.tasks, task] } : plan)); setTaskPlan(""); }
  async function exportVisitHistory() { setExporting(true); setError(""); try { await openPdfPreview(`${root}/patients/${patientId}/export`, session.accessToken); } catch (requestError) { setError(requestError.message); } finally { setExporting(false); } }
  async function exportEncounter(encounterId) { setExportingEncounterId(encounterId); setError(""); try { await openPdfPreview(`${root}/encounters/${encounterId}/export`, session.accessToken); } catch (requestError) { setError(requestError.message); } finally { setExportingEncounterId(""); } }
  return <><Button variant="outline" size="sm" onClick={() => navigate(backPath)}><ArrowLeft className="mr-2 size-4" /> Back</Button>
    <section className="relative mt-5 overflow-hidden rounded-xl bg-slate-950 p-6 text-white shadow-panel"><div className="absolute inset-0 bg-[radial-gradient(circle_at_10%_10%,rgba(13,148,136,.32),transparent_34%)]" /><div className="relative flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><div className="flex items-center gap-2 text-xs text-teal-200"><UserRound className="size-4" /> Connected longitudinal record</div><h1 className="mt-3 text-3xl font-semibold">{patient.name}</h1><div className="mt-4 flex flex-wrap gap-4 text-sm text-slate-300"><span className="flex items-center gap-2"><Phone className="size-4 text-teal-300" />{patient.phone}</span><span className="flex items-center gap-2"><MapPin className="size-4 text-teal-300" />{patient.address}</span>{patient.insuranceProvider && <span className="flex items-center gap-2"><ShieldCheck className="size-4 text-teal-300" />{patient.insuranceProvider}</span>}</div></div>{session.user.role === "frontdesk" && <Button variant="outline" className="border-white/20 bg-white/10 text-white hover:bg-white/20 hover:text-white" onClick={exportVisitHistory} disabled={exporting}><ExternalLink className="mr-2 size-4" />{exporting ? "Preparing PDF..." : "Export visit history"}</Button>}</div></section>
    <div className="mt-6 grid gap-6 xl:grid-cols-2"><Card className="bg-white shadow-none"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><CalendarDays className="size-5 text-teal-700" /> Appointments</CardTitle><CardDescription>Every booking on this patient ID.</CardDescription></CardHeader><CardContent>{appointments.length ? <div className="space-y-3">{appointments.map((item) => <div key={item._id} className="flex justify-between gap-4 rounded-lg border p-4"><div><p className="font-medium">{item.visitType}</p><p className="mt-1 text-xs text-muted-foreground">{formatClinicDateTime(item.scheduledAt)} · {item.doctorId?.name}</p></div><Badge variant={item.status}>{item.status.replace("_", " ")}</Badge></div>)}</div> : <p className="text-sm text-muted-foreground">No appointments.</p>}</CardContent></Card>
      <Card className="bg-white shadow-none"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><FileText className="size-5 text-violet-700" /> Encounters</CardTitle><CardDescription>{session.user.role === "frontdesk" ? "Administrative encounter history without clinical note details." : "Clinical documentation, AI-assisted summaries and amendments."}</CardDescription></CardHeader><CardContent><EncounterTimeline encounters={encounters} administrativeOnly={session.user.role === "frontdesk"} onOpen={session.user.role === "doctor" ? (id) => navigate(`${root}/encounters/${id}`) : null} onExport={session.user.role === "doctor" ? exportEncounter : null} exportingId={exportingEncounterId} /></CardContent></Card></div>
    <Card className="mt-6 border-teal-100 bg-white shadow-none"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><HeartHandshake className="size-5 text-teal-700" /> Care plans & progress</CardTitle><CardDescription>Versioned plans, assigned work and recorded outcomes.</CardDescription></CardHeader><CardContent>{carePlans.length === 0 ? <div className="rounded-lg border border-dashed bg-slate-50 p-8 text-center"><p className="font-medium">No care plan yet</p></div> : <div className="space-y-4">{carePlans.map((plan) => { const open = expanded === plan._id; return <article key={plan._id} className="overflow-hidden rounded-xl border"><button type="button" className="flex w-full items-center gap-4 bg-slate-50 p-5 text-left" onClick={() => setExpanded(open ? "" : plan._id)}><HeartHandshake className="size-5 text-teal-700" /><span className="min-w-0 flex-1"><span className="block font-semibold">{plan.goal}</span><span className="mt-1 block text-xs text-muted-foreground">Target: {plan.targetMeasure} · Review: {plan.reviewCadence} · Owner: {plan.owningCareTeamMemberId?.name}</span></span>{open ? <ChevronUp className="size-4" /> : <ChevronDown className="size-4" />}</button>{open && <div className="space-y-5 p-5"><section><p className="mb-3 text-sm font-semibold">Assigned tasks & outcomes</p><TaskList tasks={plan.tasks} />{["doctor", "care_coordinator"].includes(session.user.role) && <div className="mt-3">{taskPlan === plan._id ? <TaskForm root={root} headers={headers} carePlanId={plan._id} onCreated={(task) => addTask(plan._id, task)} /> : <Button size="sm" variant="outline" onClick={() => setTaskPlan(plan._id)}>Add Task</Button>}</div>}</section><section className="border-t pt-4"><p className="text-sm font-semibold">Change history</p><div className="mt-3 space-y-3 border-l-2 border-teal-100 pl-4">{plan.history.map((entry) => <div key={entry._id}><p className="text-sm">{entry.change}</p><p className="mt-1 text-xs text-muted-foreground">{entry.actor?.name} · {day(entry.timestamp)} · {entry.reason}</p></div>)}</div></section></div>}</article>; })}</div>}</CardContent></Card>
  </>;
}
