import { useEffect, useState } from "react";
import { CheckCircle2, Heart } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { apiRequest } from "@/api/client";

export function PortalActivationPage() {
  const { token } = useParams(); const [state, setState] = useState({ loading: true, valid: false, patientName: "", error: "" }); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [saving, setSaving] = useState(false); const [complete, setComplete] = useState(false);
  useEffect(() => { apiRequest(`/patient-portal/activate/${token}`).then((data) => setState({ loading: false, valid: true, patientName: data.patientName, error: "" })).catch((e) => setState({ loading: false, valid: false, patientName: "", error: e.message })); }, [token]);
  async function submit(e) { e.preventDefault(); if (password !== confirm) return setState((s) => ({ ...s, error: "Your passwords do not match." })); setSaving(true); setState((s) => ({ ...s, error: "" })); try { await apiRequest(`/patient-portal/activate/${token}`, { method: "POST", body: JSON.stringify({ password }) }); setComplete(true); } catch (e) { setState((s) => ({ ...s, error: e.message })); } finally { setSaving(false); } }
  return <main className="min-h-screen bg-gradient-to-b from-teal-50 via-slate-50 to-white px-4 py-8 sm:py-14"><div className="mx-auto w-full max-w-md"><div className="mb-8 text-center"><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-teal-700 text-white shadow-lg"><Heart className="size-7" /></span><p className="mt-5 text-sm font-semibold text-teal-700">Meridian Health Connect</p><h1 className="mt-2 text-3xl font-bold">Set your password</h1></div><section className="rounded-2xl border bg-white p-6 shadow-sm sm:p-8">{state.loading ? <p className="text-lg text-slate-600">Checking your invitation…</p> : complete ? <div className="text-center"><CheckCircle2 className="mx-auto size-12 text-teal-700" /><h2 className="mt-4 text-2xl font-bold">Your account is ready</h2><p className="mt-3 text-lg leading-7 text-slate-600">You can now sign in to your patient portal.</p><Link className="mt-6 flex min-h-12 items-center justify-center rounded-lg bg-teal-700 px-5 text-base font-bold text-white" to="/portal/login">Go to patient sign in</Link></div> : !state.valid ? <div><h2 className="text-xl font-bold">We could not open this invitation</h2><p className="mt-3 text-lg leading-7 text-slate-600">{state.error}</p><p className="mt-5 text-base text-slate-600">Please contact your clinic and ask them to send a new portal invitation.</p></div> : <form onSubmit={submit} className="space-y-5"><p className="text-lg leading-7 text-slate-600">Hello {state.patientName}. Choose a password to activate your portal.</p><div><label className="text-base font-semibold" htmlFor="new-password">New password</label><input id="new-password" className="mt-2 min-h-12 w-full rounded-lg border px-4 text-base outline-none focus:border-teal-700 focus:ring-2 focus:ring-teal-200" type="password" minLength="8" autoComplete="new-password" value={password} onChange={(e) => setPassword(e.target.value)} required /></div><div><label className="text-base font-semibold" htmlFor="confirm-password">Confirm password</label><input id="confirm-password" className="mt-2 min-h-12 w-full rounded-lg border px-4 text-base outline-none focus:border-teal-700 focus:ring-2 focus:ring-teal-200" type="password" minLength="8" autoComplete="new-password" value={confirm} onChange={(e) => setConfirm(e.target.value)} required /></div>{state.error && <p className="rounded-lg bg-red-50 p-4 text-base text-red-800">{state.error}</p>}<button className="min-h-12 w-full rounded-lg bg-teal-700 px-5 text-base font-bold text-white" disabled={saving}>{saving ? "Activating..." : "Activate account"}</button></form>}</section></div></main>;
}
