import { useState } from "react";
import { Heart, LockKeyhole } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { apiRequest } from "@/api/client";
import { savePortalSession } from "@/portal/portal-session";

export function PortalLoginPage() {
  const navigate = useNavigate(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(e) { e.preventDefault(); setLoading(true); setError(""); try { const session = await apiRequest("/patient-portal/login", { method: "POST", body: JSON.stringify({ email, password }) }); savePortalSession(session); navigate("/portal", { replace: true }); } catch (e) { setError(e.message); } finally { setLoading(false); } }
  return <main className="min-h-screen bg-gradient-to-b from-teal-50 via-slate-50 to-white px-4 py-8 text-slate-900 sm:px-6 sm:py-14"><div className="mx-auto w-full max-w-md"><div className="mb-8 text-center"><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-teal-700 text-white shadow-lg"><Heart className="size-7" /></span><p className="mt-5 text-sm font-semibold text-teal-700">Meridian Health Connect</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Welcome back</h1><p className="mt-3 text-lg leading-7 text-slate-600">Sign in to your patient portal.</p></div><form onSubmit={submit} className="rounded-2xl border bg-white p-6 shadow-sm sm:p-8"><div className="space-y-5"><div><label className="text-base font-semibold" htmlFor="portal-email">Email address</label><input id="portal-email" className="mt-2 min-h-12 w-full rounded-lg border px-4 text-base outline-none focus:border-teal-700 focus:ring-2 focus:ring-teal-200" type="email" autoComplete="email" value={email} onChange={(e) => setEmail(e.target.value)} required /></div><div><label className="text-base font-semibold" htmlFor="portal-password">Password</label><input id="portal-password" className="mt-2 min-h-12 w-full rounded-lg border px-4 text-base outline-none focus:border-teal-700 focus:ring-2 focus:ring-teal-200" type="password" autoComplete="current-password" value={password} onChange={(e) => setPassword(e.target.value)} required /></div>{error && <p className="rounded-lg bg-red-50 p-4 text-base leading-6 text-red-800">{error}</p>}<button className="flex min-h-12 w-full items-center justify-center gap-2 rounded-lg bg-teal-700 px-5 text-base font-bold text-white transition hover:bg-teal-800 focus:outline-none focus:ring-4 focus:ring-teal-200" disabled={loading}><LockKeyhole className="size-5" />{loading ? "Signing in..." : "Sign in"}</button></div></form><p className="mt-6 text-center text-base leading-6 text-slate-600">Need an account? Your clinic will email you an invitation to get started.</p><p className="mt-3 text-center"><Link className="text-base font-semibold text-teal-800 underline underline-offset-4" to="/login">Staff sign in</Link></p></div></main>;
}
