import { useEffect, useMemo, useState } from "react";
import { CalendarDays, Clock3, Plus, Trash2 } from "lucide-react";
import { useParams } from "react-router-dom";
import { apiRequest } from "@/api/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useAuth } from "@/context/auth-context";
import { useRealtimeRevision } from "@/realtime/useRealtimeRevision";

const days = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
const localDate = () => new Date(Date.now() + 5 * 3600000).toISOString().slice(0, 10);
const monday = (date) => { const value = new Date(`${date}T12:00:00Z`); value.setUTCDate(value.getUTCDate() - (value.getUTCDay() + 6) % 7); return value.toISOString().slice(0, 10); };
const fmt = (value) => new Intl.DateTimeFormat("en-PK", { dateStyle: "medium", timeStyle: "short", hour12: true, timeZone: "Asia/Karachi" }).format(new Date(value));
const formatShiftTime = (value) => {
  const [hourText, minute] = value.split(":");
  const hour = Number(hourText);
  return `${hour % 12 || 12}:${minute} ${hour < 12 ? "AM" : "PM"}`;
};
const hours = (minutes) => `${Math.floor(minutes / 60)}h ${minutes % 60}m`;
const initial = { staffId: "", kind: "weekly", dayOfWeek: "1", date: localDate(), startTime: "09:00", endTime: "14:00", cancelled: false };

export function ShiftManagementPage() {
  const { tenantSlug, locationSlug } = useParams(); const { session } = useAuth(); const root = `/${tenantSlug}/${locationSlug}`;
  const headers = useMemo(() => ({ Authorization: `Bearer ${session.accessToken}` }), [session.accessToken]);
  const revision = useRealtimeRevision(["shift:scheduled", "attendance:updated", "staff:created", "staff:updated"]);
  const [staff, setStaff] = useState([]); const [rules, setRules] = useState([]); const [report, setReport] = useState(null); const [week, setWeek] = useState(monday(localDate())); const [form, setForm] = useState(initial); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [saving, setSaving] = useState(false);
  const load = () => Promise.all([apiRequest(`${root}/users`, { headers }), apiRequest(`${root}/shifts/schedule`, { headers }), apiRequest(`${root}/shifts/report?weekStart=${week}`, { headers })]).then(([users, schedule, attendance]) => { setStaff((users.users || []).filter((user) => user.role === "frontdesk")); setRules(schedule.rules || []); setReport(attendance); }).catch((e) => setError(e.message));
  useEffect(() => { load(); const timer = setInterval(load, 60000); return () => clearInterval(timer); }, [root, headers, revision, week]);
  async function save(event) { event.preventDefault(); setSaving(true); setError(""); setNotice(""); try { await apiRequest(`${root}/shifts/schedule`, { method: "PUT", headers, body: JSON.stringify({ ...form, dayOfWeek: Number(form.dayOfWeek) }) }); setNotice("Shift schedule saved."); await load(); } catch (e) { setError(e.message); } finally { setSaving(false); } }
  async function remove(id) { setError(""); try { await apiRequest(`${root}/shifts/schedule/${id}`, { method: "DELETE", headers }); setNotice("Shift rule removed."); await load(); } catch (e) { setError(e.message); } }
  return <div className="space-y-6"><div><p className="text-sm font-semibold text-teal-700">Clinic administration</p><h1 className="mt-1 text-3xl font-bold">Front-desk shifts & attendance</h1><p className="mt-2 text-slate-600">Plan weekly coverage, make one-day changes, and compare actual attendance. Times use Pakistan time.</p></div>{error && <p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{notice && <p className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">{notice}</p>}
    <div className="grid gap-6 xl:grid-cols-[minmax(300px,0.8fr)_minmax(0,1.2fr)]"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Plus className="size-5 text-teal-700" />Set a shift</CardTitle></CardHeader><CardContent><form onSubmit={save} className="space-y-4"><div className="space-y-2"><Label>Front-desk member</Label><Select value={form.staffId} onValueChange={(staffId) => setForm({ ...form, staffId })}><SelectTrigger><SelectValue placeholder="Choose staff" /></SelectTrigger><SelectContent>{staff.map((member) => <SelectItem key={member.id} value={member.id}>{member.name}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Shift pattern</Label><Select value={form.kind} onValueChange={(kind) => setForm({ ...form, kind, cancelled: false })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="weekly">Every week</SelectItem><SelectItem value="date">One specific date</SelectItem></SelectContent></Select></div>{form.kind === "weekly" ? <div className="space-y-2"><Label>Day</Label><Select value={form.dayOfWeek} onValueChange={(dayOfWeek) => setForm({ ...form, dayOfWeek })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{days.map((day, index) => <SelectItem key={day} value={String(index)}>{day}</SelectItem>)}</SelectContent></Select></div> : <><div className="space-y-2"><Label>Date to change</Label><Input type="date" value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} required /></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" className="size-4 accent-teal-700" checked={form.cancelled} onChange={(e) => setForm({ ...form, cancelled: e.target.checked })} />Cancel this member’s shift for this date</label></>}{!form.cancelled && <div className="grid grid-cols-2 gap-3"><div className="space-y-2"><Label>Starts</Label><Input type="time" value={form.startTime} onChange={(e) => setForm({ ...form, startTime: e.target.value })} required /></div><div className="space-y-2"><Label>Ends</Label><Input type="time" value={form.endTime} onChange={(e) => setForm({ ...form, endTime: e.target.value })} required /></div></div>}<p className="text-xs text-slate-500">An end time earlier than the start time means the shift ends the next day. Saving the same member/day updates their existing rule.</p><Button type="submit" className="w-full bg-teal-700" disabled={!form.staffId || saving}>{saving ? "Saving..." : "Save shift"}</Button></form></CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><CalendarDays className="size-5 text-teal-700" />Current rules</CardTitle></CardHeader><CardContent><div className="space-y-2">{rules.length ? rules.map((rule) => <div key={rule.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg border p-3"><div><p className="font-semibold">{staff.find((member) => member.id === rule.staffId)?.name || "Staff"}</p><p className="text-xs text-slate-600">{rule.kind === "weekly" ? `Every ${days[rule.dayOfWeek]}` : rule.date} · {rule.cancelled ? "Off / cancelled" : `${formatShiftTime(rule.startTime)}–${formatShiftTime(rule.endTime)}`}</p></div><Button size="sm" variant="outline" aria-label="Remove shift rule" onClick={() => remove(rule.id)}><Trash2 className="size-4" /></Button></div>) : <p className="rounded-lg border border-dashed p-6 text-center text-sm text-slate-500">No shift rules yet.</p>}</div></CardContent></Card></div>
    <Card><CardHeader><div className="flex flex-wrap items-end justify-between gap-3"><div><CardTitle className="flex items-center gap-2"><Clock3 className="size-5 text-teal-700" />Attendance report</CardTitle><p className="mt-1 text-sm text-slate-600">Weekly totals and actual sessions. Late means more than 10 minutes after planned start.</p></div><div><Label>Week starting Monday</Label><Input className="mt-1" type="date" value={week} onChange={(e) => setWeek(monday(e.target.value))} /></div></div></CardHeader><CardContent><div className="space-y-3">{report?.staff?.map((member) => <div key={member.id} className="rounded-xl border p-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-semibold">{member.name}</p><div className="flex gap-2 text-xs"><span className="rounded-full bg-teal-50 px-3 py-1 text-teal-800">Today {hours(member.todayMinutes)}</span><span className="rounded-full bg-blue-50 px-3 py-1 text-blue-800">Week {hours(member.weekMinutes)}</span></div></div><div className="mt-3 space-y-2">{member.sessions.map((item) => <div key={item.id} className="flex flex-wrap items-center gap-2 text-sm text-slate-600"><span>{fmt(item.clockInAt)} → {item.clockOutAt ? fmt(item.clockOutAt) : "On duty"} ({hours(item.workedMinutes)})</span>{!item.plannedStartAt && <span className="rounded bg-slate-100 px-2 py-0.5 text-xs">Unscheduled</span>}{item.lateMinutes > 10 && <span className="rounded bg-amber-50 px-2 py-0.5 text-xs text-amber-800">Late {item.lateMinutes}m</span>}{item.extraMinutes > 0 && <span className="rounded bg-violet-50 px-2 py-0.5 text-xs text-violet-800">Extra {item.extraMinutes}m</span>}</div>)}{member.shifts.filter((item) => item.absent).map((item) => <p key={item.id + item.date} className="text-sm text-red-700">Missed shift: {item.date} {formatShiftTime(item.startTime)}–{formatShiftTime(item.endTime)}</p>)}{!member.sessions.length && !member.shifts.some((item) => item.absent) && <p className="text-sm text-slate-400">No recorded hours this week.</p>}</div></div>)}</div></CardContent></Card>
  </div>;
}
